/**
 * Vehicle Fitment API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Fitment tag key/value pair used for product applicability matching
 */
export interface FitmentTagDto { 
    /**
     * Tag category
     */
    tagType: FitmentTagDtoTagTypeEnum;
    /**
     * Tag value for the selected category
     */
    tagValue: string;
}
export enum FitmentTagDtoTagTypeEnum {
    Make = 'MAKE',
    Model = 'MODEL',
    YearRange = 'YEAR_RANGE',
    TireSize = 'TIRE_SIZE',
    AxlePosition = 'AXLE_POSITION',
    EngineSize = 'ENGINE_SIZE',
    TrimLevel = 'TRIM_LEVEL'
};



function isOptionalFitmentTagDtoPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type FitmentTagDtoOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createFitmentTagDtoPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createFitmentTagDtoOptionalProperties(
    ...properties: FitmentTagDtoOptionalProperty[]
): ReadonlyArray<FitmentTagDtoOptionalProperty> {
    return properties;
}

export function instanceOfFitmentTagDto(value: object): value is FitmentTagDto {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createFitmentTagDtoPropertyNames('tagType', 'tagValue', );
    const optionalStringProperties = createFitmentTagDtoOptionalProperties({ name: 'tagType', nullable: false }, { name: 'tagValue', nullable: false }, );
    const optionalNumberProperties = createFitmentTagDtoOptionalProperties();
    const optionalBooleanProperties = createFitmentTagDtoOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalFitmentTagDtoPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalFitmentTagDtoPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalFitmentTagDtoPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

