export * from './cRMAccounts.service';
import { CRMAccountsService } from './cRMAccounts.service';
export * from './cRMCommunicationPreferences.service';
import { CRMCommunicationPreferencesService } from './cRMCommunicationPreferences.service';
export * from './cRMContacts.service';
import { CRMContactsService } from './cRMContacts.service';
export * from './cRMPartyRelationships.service';
import { CRMPartyRelationshipsService } from './cRMPartyRelationships.service';
export * from './cRMPersonLinkReconciliation.service';
import { CRMPersonLinkReconciliationService } from './cRMPersonLinkReconciliation.service';
export * from './cRMPersons.service';
import { CRMPersonsService } from './cRMPersons.service';
export * from './cRMSnapshots.service';
import { CRMSnapshotsService } from './cRMSnapshots.service';
export * from './cRMVehicles.service';
import { CRMVehiclesService } from './cRMVehicles.service';
export * from './customerAPI.service';
import { CustomerAPIService } from './customerAPI.service';
export * from './customerBulkIngestAPI.service';
import { CustomerBulkIngestAPIService } from './customerBulkIngestAPI.service';
export * from './customerRequirements.service';
import { CustomerRequirementsService } from './customerRequirements.service';
export * from './promotionRedemptions.service';
import { PromotionRedemptionsService } from './promotionRedemptions.service';
export const APIS = [CRMAccountsService, CRMCommunicationPreferencesService, CRMContactsService, CRMPartyRelationshipsService, CRMPersonLinkReconciliationService, CRMPersonsService, CRMSnapshotsService, CRMVehiclesService, CustomerAPIService, CustomerBulkIngestAPIService, CustomerRequirementsService, PromotionRedemptionsService];
