export * from './cRMAccounts.service';
import { CRMAccountsService } from './cRMAccounts.service';
export * from './cRMCommunicationPreferences.service';
import { CRMCommunicationPreferencesService } from './cRMCommunicationPreferences.service';
export * from './cRMContacts.service';
import { CRMContactsService } from './cRMContacts.service';
export * from './cRMFollowUps.service';
import { CRMFollowUpsService } from './cRMFollowUps.service';
export * from './cRMInquiries.service';
import { CRMInquiriesService } from './cRMInquiries.service';
export * from './cRMInteractions.service';
import { CRMInteractionsService } from './cRMInteractions.service';
export * from './cRMMarketingConsent.service';
import { CRMMarketingConsentService } from './cRMMarketingConsent.service';
export * from './cRMPartyRelationships.service';
import { CRMPartyRelationshipsService } from './cRMPartyRelationships.service';
export * from './cRMPersonLinkReconciliation.service';
import { CRMPersonLinkReconciliationService } from './cRMPersonLinkReconciliation.service';
export * from './cRMPersons.service';
import { CRMPersonsService } from './cRMPersons.service';
export * from './cRMPublicInquiry.service';
import { CRMPublicInquiryService } from './cRMPublicInquiry.service';
export * from './cRMSegments.service';
import { CRMSegmentsService } from './cRMSegments.service';
export * from './cRMSnapshots.service';
import { CRMSnapshotsService } from './cRMSnapshots.service';
export * from './cRMSuppression.service';
import { CRMSuppressionService } from './cRMSuppression.service';
export * from './cRMTags.service';
import { CRMTagsService } from './cRMTags.service';
export * from './cRMVehicles.service';
import { CRMVehiclesService } from './cRMVehicles.service';
export * from './customerAPI.service';
import { CustomerAPIService } from './customerAPI.service';
export * from './customerBulkIngestAPI.service';
import { CustomerBulkIngestAPIService } from './customerBulkIngestAPI.service';
export * from './customerRequirements.service';
import { CustomerRequirementsService } from './customerRequirements.service';
export * from './promotionRedemptions.service';
import { PromotionRedemptionsService } from './promotionRedemptions.service';
export const APIS = [CRMAccountsService, CRMCommunicationPreferencesService, CRMContactsService, CRMFollowUpsService, CRMInquiriesService, CRMInteractionsService, CRMMarketingConsentService, CRMPartyRelationshipsService, CRMPersonLinkReconciliationService, CRMPersonsService, CRMPublicInquiryService, CRMSegmentsService, CRMSnapshotsService, CRMSuppressionService, CRMTagsService, CRMVehiclesService, CustomerAPIService, CustomerBulkIngestAPIService, CustomerRequirementsService, PromotionRedemptionsService];
