/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Per-customer aged receivables row with bucketed open invoice balances. Age is measured from the invoice due date, falling back to the invoice date when no due date is recorded; invoices due today or later are notYetDue, the four late buckets are overdue money.
 */
export interface AgedReceivablesRow {
    /**
     * Customer (party) UUID
     */
    customerId: string;
    /**
     * Customer display name from the customer replica; null when the party is not yet known
     */
    customerName?: string;
    /**
     * Customer number from the customer replica; null when the party is not yet known
     */
    customerReference?: string;
    /**
     * Outstanding 1-30 days past due
     */
    days1To30: number;
    /**
     * Outstanding 31-60 days past due
     */
    days31To60: number;
    /**
     * Outstanding 61-90 days past due
     */
    days61To90: number;
    /**
     * Outstanding more than 90 days past due
     */
    days90Plus: number;
    /**
     * Outstanding not yet due: due today or later (due today is not overdue)
     */
    notYetDue: number;
    /**
     * Overdue: the sum of days1To30, days31To60, days61To90 and days90Plus
     */
    overdue: number;
    /**
     * Total outstanding for the customer: notYetDue + overdue
     */
    totalOutstanding: number;
}

function isOptionalAgedReceivablesRowPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type AgedReceivablesRowOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createAgedReceivablesRowPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createAgedReceivablesRowOptionalProperties(
    ...properties: AgedReceivablesRowOptionalProperty[]
): ReadonlyArray<AgedReceivablesRowOptionalProperty> {
    return properties;
}

export function instanceOfAgedReceivablesRow(value: object): value is AgedReceivablesRow {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createAgedReceivablesRowPropertyNames('customerId', 'days1To30', 'days31To60', 'days61To90', 'days90Plus', 'notYetDue', 'overdue', 'totalOutstanding', );
    const optionalStringProperties = createAgedReceivablesRowOptionalProperties({ name: 'customerId', nullable: false }, { name: 'customerName', nullable: false }, { name: 'customerReference', nullable: false }, );
    const optionalNumberProperties = createAgedReceivablesRowOptionalProperties({ name: 'days1To30', nullable: false }, { name: 'days31To60', nullable: false }, { name: 'days61To90', nullable: false }, { name: 'days90Plus', nullable: false }, { name: 'notYetDue', nullable: false }, { name: 'overdue', nullable: false }, { name: 'totalOutstanding', nullable: false }, );
    const optionalBooleanProperties = createAgedReceivablesRowOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalAgedReceivablesRowPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalAgedReceivablesRowPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalAgedReceivablesRowPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

