/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgingSummary } from './agingSummary';
import { AgedPayablesRow } from './agedPayablesRow';


/**
 * Aged Payables report with per-vendor bucketed open vendor-bill balances
 */
export interface AgedPayablesReport {
    /**
     * Date the payables aging is reported as of (inclusive)
     */
    asOfDate: string;
    /**
     * Timestamp when the report was generated (ISO 8601)
     */
    generatedAt: string;
    /**
     * Per-vendor aging rows ordered by vendor name; empty when no open payables exist
     */
    rows: Array<AgedPayablesRow>;
    totals: AgingSummary;
}

function isOptionalAgedPayablesReportPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type AgedPayablesReportOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createAgedPayablesReportPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createAgedPayablesReportOptionalProperties(
    ...properties: AgedPayablesReportOptionalProperty[]
): ReadonlyArray<AgedPayablesReportOptionalProperty> {
    return properties;
}

export function instanceOfAgedPayablesReport(value: object): value is AgedPayablesReport {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createAgedPayablesReportPropertyNames('asOfDate', 'generatedAt', 'rows', 'totals', );
    const optionalStringProperties = createAgedPayablesReportOptionalProperties({ name: 'asOfDate', nullable: false }, { name: 'generatedAt', nullable: false }, );
    const optionalNumberProperties = createAgedPayablesReportOptionalProperties();
    const optionalBooleanProperties = createAgedPayablesReportOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalAgedPayablesReportPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalAgedPayablesReportPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalAgedPayablesReportPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

