/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A bank transaction: what the bank reported, its provenance, dedupe state and links
 */
export interface BankTransactionResponse {
    /**
     * GL account code
     */
    accountCode?: string;
    /**
     * GL account name
     */
    accountName?: string;
    /**
     * True when a feed delivered the row inside a FINALIZED reconciliation window (phase 2)
     */
    arrivedAfterApproval?: boolean;
    /**
     * Authorization date, when the source knows it
     */
    authorizedDate?: string;
    /**
     * Bank transaction id
     */
    bankTransactionId?: string;
    /**
     * The source\'s category, informational only
     */
    categoryHint?: string;
    /**
     * Check number
     */
    checkNumber?: string;
    /**
     * Provenance label of the source
     */
    connectorCode?: string;
    /**
     * Counterparty, when the source names one
     */
    counterpartyName?: string;
    /**
     * ISO 4217 code
     */
    currency?: string;
    /**
     * Description as delivered
     */
    description?: string;
    /**
     * The earlier row this one may duplicate, or was confirmed to duplicate
     */
    duplicateOfBankTransactionId?: string;
    /**
     * When the row was excluded
     */
    excludedAt?: string;
    /**
     * Who excluded the row
     */
    excludedBy?: string;
    /**
     * Why the row was excluded
     */
    exclusionReason?: string;
    /**
     * The last change the source reported
     */
    feedChange?: BankTransactionResponseFeedChangeEnum;
    /**
     * SHA-256 dedupe fingerprint
     */
    fingerprint?: string;
    /**
     * When the source first reported the row
     */
    firstObservedAt?: string;
    /**
     * GL bank account id
     */
    glAccountId?: string;
    /**
     * When the source last reported the row
     */
    lastObservedAt?: string;
    /**
     * The active reconciliation match holding the row; null until matching exists (S4)
     */
    matchId?: string;
    /**
     * Upper-cased, punctuation-stripped copy used only for dedupe
     */
    normalizedDescription?: string;
    /**
     * The first description the source delivered, when it later changed
     */
    originalDescription?: string;
    /**
     * The open outstanding item holding the row; null until outstanding items exist (S4)
     */
    outstandingItemId?: string;
    /**
     * The bank\'s reference
     */
    reference?: string;
    /**
     * When the source removed the row (phase 2)
     */
    removedAt?: string;
    /**
     * PENDING rows are visible but never matchable
     */
    settlementState?: BankTransactionResponseSettlementStateEnum;
    /**
     * Signed amount, positive = money into the account
     */
    signedAmount?: number;
    /**
     * Where the row came from
     */
    sourceKind?: BankTransactionResponseSourceKindEnum;
    /**
     * Provenance reference: the import id for a file; null for manual entry
     */
    sourceRef?: string;
    /**
     * 1-based position in the source
     */
    sourceRowNumber?: number;
    /**
     * The source\'s id for the transaction, when it has one
     */
    sourceTransactionId?: string;
    /**
     * The statement that carried the row; null for a feed row
     */
    statementId?: string;
    /**
     * Row status
     */
    status?: BankTransactionResponseStatusEnum;
    /**
     * The pending row this posted row replaced
     */
    supersedesBankTransactionId?: string;
    /**
     * The bank\'s posting date
     */
    transactionDate?: string;
    /**
     * Optimistic-lock version; send it back on a review, exclude or restore
     */
    version?: number;
}
export enum BankTransactionResponseFeedChangeEnum {
    Added = 'ADDED',
    Modified = 'MODIFIED',
    Removed = 'REMOVED'
};
export enum BankTransactionResponseSettlementStateEnum {
    Pending = 'PENDING',
    Posted = 'POSTED'
};
export enum BankTransactionResponseSourceKindEnum {
    FileImport = 'FILE_IMPORT',
    ManualEntry = 'MANUAL_ENTRY',
    BankFeed = 'BANK_FEED'
};
export enum BankTransactionResponseStatusEnum {
    Unmatched = 'UNMATCHED',
    PossibleDuplicate = 'POSSIBLE_DUPLICATE',
    Matched = 'MATCHED',
    Excluded = 'EXCLUDED',
    RemovedBySource = 'REMOVED_BY_SOURCE'
};



function isOptionalBankTransactionResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type BankTransactionResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createBankTransactionResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createBankTransactionResponseOptionalProperties(
    ...properties: BankTransactionResponseOptionalProperty[]
): ReadonlyArray<BankTransactionResponseOptionalProperty> {
    return properties;
}

export function instanceOfBankTransactionResponse(value: object): value is BankTransactionResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createBankTransactionResponsePropertyNames();
    const optionalStringProperties = createBankTransactionResponseOptionalProperties({ name: 'accountCode', nullable: false }, { name: 'accountName', nullable: false }, { name: 'authorizedDate', nullable: false }, { name: 'bankTransactionId', nullable: false }, { name: 'categoryHint', nullable: false }, { name: 'checkNumber', nullable: false }, { name: 'connectorCode', nullable: false }, { name: 'counterpartyName', nullable: false }, { name: 'currency', nullable: false }, { name: 'description', nullable: false }, { name: 'duplicateOfBankTransactionId', nullable: false }, { name: 'excludedAt', nullable: false }, { name: 'excludedBy', nullable: false }, { name: 'exclusionReason', nullable: false }, { name: 'feedChange', nullable: false }, { name: 'fingerprint', nullable: false }, { name: 'firstObservedAt', nullable: false }, { name: 'glAccountId', nullable: false }, { name: 'lastObservedAt', nullable: false }, { name: 'matchId', nullable: false }, { name: 'normalizedDescription', nullable: false }, { name: 'originalDescription', nullable: false }, { name: 'outstandingItemId', nullable: false }, { name: 'reference', nullable: false }, { name: 'removedAt', nullable: false }, { name: 'settlementState', nullable: false }, { name: 'sourceKind', nullable: false }, { name: 'sourceRef', nullable: false }, { name: 'sourceTransactionId', nullable: false }, { name: 'statementId', nullable: false }, { name: 'status', nullable: false }, { name: 'supersedesBankTransactionId', nullable: false }, { name: 'transactionDate', nullable: false }, );
    const optionalNumberProperties = createBankTransactionResponseOptionalProperties({ name: 'signedAmount', nullable: false }, { name: 'sourceRowNumber', nullable: false }, { name: 'version', nullable: false }, );
    const optionalBooleanProperties = createBankTransactionResponseOptionalProperties({ name: 'arrivedAfterApproval', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalBankTransactionResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalBankTransactionResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalBankTransactionResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

