/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankOpeningBalanceItem } from './bankOpeningBalanceItem';


/**
 * A bank account\'s opening balance as posted
 */
export interface BankOpeningBalanceResponse {
    /**
     * The bank account\'s code
     */
    accountCode: string;
    /**
     * The cutover date the entry is dated on
     */
    asOfDate: string;
    /**
     * The ledger balance the entry sets: statement balance + deposits in transit − outstanding checks
     */
    bookBalance: number;
    /**
     * The ISO 4217 code of both balances and every item amount
     */
    currencyCode: string;
    /**
     * The bank account
     */
    glAccountId: string;
    /**
     * The journal entry the command posted
     */
    journalEntryId: string;
    /**
     * That entry\'s number
     */
    journalEntryNumber: string;
    /**
     * The outstanding items, each with its own bank line; empty when there are none
     */
    outstandingItems: Array<BankOpeningBalanceItem>;
    /**
     * True when this answers a replayed requestId with the first result
     */
    replayed?: boolean;
    /**
     * The bank\'s balance at the end of asOfDate
     */
    statementBalance: number;
}

function isOptionalBankOpeningBalanceResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type BankOpeningBalanceResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createBankOpeningBalanceResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createBankOpeningBalanceResponseOptionalProperties(
    ...properties: BankOpeningBalanceResponseOptionalProperty[]
): ReadonlyArray<BankOpeningBalanceResponseOptionalProperty> {
    return properties;
}

export function instanceOfBankOpeningBalanceResponse(value: object): value is BankOpeningBalanceResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createBankOpeningBalanceResponsePropertyNames('accountCode', 'asOfDate', 'bookBalance', 'currencyCode', 'glAccountId', 'journalEntryId', 'journalEntryNumber', 'outstandingItems', 'statementBalance', );
    const optionalStringProperties = createBankOpeningBalanceResponseOptionalProperties({ name: 'accountCode', nullable: false }, { name: 'asOfDate', nullable: false }, { name: 'currencyCode', nullable: false }, { name: 'glAccountId', nullable: false }, { name: 'journalEntryId', nullable: false }, { name: 'journalEntryNumber', nullable: false }, );
    const optionalNumberProperties = createBankOpeningBalanceResponseOptionalProperties({ name: 'bookBalance', nullable: false }, { name: 'statementBalance', nullable: false }, );
    const optionalBooleanProperties = createBankOpeningBalanceResponseOptionalProperties({ name: 'replayed', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalBankOpeningBalanceResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalBankOpeningBalanceResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalBankOpeningBalanceResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

