/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Opening + activity against closing for one statement
 */
export interface BankImportSegmentTotal {
    /**
     * Sum of the counted rows
     */
    activityTotal: number;
    /**
     * Closing balance
     */
    closingBalance: number;
    /**
     * Expected closing − closing
     */
    difference: number;
    /**
     * Last day
     */
    endDate: string;
    /**
     * Opening + activity
     */
    expectedClosing: number;
    /**
     * Opening balance
     */
    openingBalance: number;
    /**
     * First day
     */
    startDate: string;
    /**
     * Whether the difference is within one minor unit (E1)
     */
    ties: boolean;
    /**
     * Rows counted in the segment
     */
    transactionCount: number;
}

function isOptionalBankImportSegmentTotalPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type BankImportSegmentTotalOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createBankImportSegmentTotalPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createBankImportSegmentTotalOptionalProperties(
    ...properties: BankImportSegmentTotalOptionalProperty[]
): ReadonlyArray<BankImportSegmentTotalOptionalProperty> {
    return properties;
}

export function instanceOfBankImportSegmentTotal(value: object): value is BankImportSegmentTotal {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createBankImportSegmentTotalPropertyNames('activityTotal', 'closingBalance', 'difference', 'endDate', 'expectedClosing', 'openingBalance', 'startDate', 'ties', 'transactionCount', );
    const optionalStringProperties = createBankImportSegmentTotalOptionalProperties({ name: 'endDate', nullable: false }, { name: 'startDate', nullable: false }, );
    const optionalNumberProperties = createBankImportSegmentTotalOptionalProperties({ name: 'activityTotal', nullable: false }, { name: 'closingBalance', nullable: false }, { name: 'difference', nullable: false }, { name: 'expectedClosing', nullable: false }, { name: 'openingBalance', nullable: false }, { name: 'transactionCount', nullable: false }, );
    const optionalBooleanProperties = createBankImportSegmentTotalOptionalProperties({ name: 'ties', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalBankImportSegmentTotalPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalBankImportSegmentTotalPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalBankImportSegmentTotalPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

