/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CancellationRequest { 
    orderId?: string;
    invoiceId?: string;
    cancellationType: CancellationRequestCancellationTypeEnum;
    beforeSnapshot: string;
    afterSnapshot: string;
    partialPaymentInfo?: string;
    actorId?: string;
    actorRole: string;
    reason: string;
}
export enum CancellationRequestCancellationTypeEnum {
    OrderCancelled = 'ORDER_CANCELLED',
    InvoiceCancelled = 'INVOICE_CANCELLED',
    PaymentFailed = 'PAYMENT_FAILED'
};



function isOptionalCancellationRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CancellationRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCancellationRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCancellationRequestOptionalProperties(
    ...properties: CancellationRequestOptionalProperty[]
): ReadonlyArray<CancellationRequestOptionalProperty> {
    return properties;
}

export function instanceOfCancellationRequest(value: object): value is CancellationRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCancellationRequestPropertyNames('cancellationType', 'beforeSnapshot', 'afterSnapshot', 'actorRole', 'reason', );
    const optionalStringProperties = createCancellationRequestOptionalProperties({ name: 'orderId', nullable: false }, { name: 'invoiceId', nullable: false }, { name: 'cancellationType', nullable: false }, { name: 'beforeSnapshot', nullable: false }, { name: 'afterSnapshot', nullable: false }, { name: 'partialPaymentInfo', nullable: false }, { name: 'actorId', nullable: false }, { name: 'actorRole', nullable: false }, { name: 'reason', nullable: false }, );
    const optionalNumberProperties = createCancellationRequestOptionalProperties();
    const optionalBooleanProperties = createCancellationRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCancellationRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCancellationRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCancellationRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

