/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Invoiced-vs-collected analytics for one date window. invoiced and collected are different invoice cohorts (see field descriptions) — do not present collectionRatePct as a cohort collection rate. collected is applied-to-A/R net of reversals recorded in the window, not cash received: it excludes deposit-credit and customer-credit settlement. Refunds have no dedicated figure (see #1620), but a refund accompanied by a payment-application reversal — the commonest shape — reduces collected in the window that reversal was recorded; standalone and credit-balance refunds are not reflected.
 */
export interface CollectionsAnalyticsReport { 
    /**
     * GROSS sum of PaymentApplicationReversal.amount whose reversedAt falls in the window, as a positive number; this amount has already been subtracted from collected. Reported so a consumer seeing a dip in collected can attribute it to reversals without a second call. 0 when no reversals were recorded in the window
     */
    applicationReversals: number;
    /**
     * Payment amounts APPLIED to accounts receivable within the window, NET of application reversals recorded within the window — this is NOT cash received. Computed as the sum of PaymentApplication.appliedAmount whose applicationTimestamp falls in the window, minus the sum of PaymentApplicationReversal.amount whose reversedAt falls in the window (movement basis: a January payment reversed in March reduces March and never restates January, so sub-windows remain additive). Settlement by deposit credit or customer credit is EXCLUDED, because that cash was received when the deposit was taken rather than when the credit was drawn down, so a window in which deposit-funded invoices finalize shows collectionRatePct understated. Refunds have no dedicated figure in this endpoint (see #1620): where a refund is accompanied by a payment-application reversal — the commonest shape — that reversal reduces collected in the window the reversal was recorded, per the movement basis above, whereas standalone refunds and credit-balance refunds are not reflected at all. May be NEGATIVE in a heavy-reversal window; it is deliberately not clamped. 0 when nothing was applied or reversed in the window
     */
    collected: number;
    /**
     * collected divided by invoiced, times 100, rounded HALF_UP to 2 decimals; null when invoiced is zero (the ratio is undefined — never a divide-by-zero error and never a misleading 0). May be NEGATIVE when in-window application reversals exceed in-window applications (see collected); it is not clamped. HALF_UP rounds away from zero for negative values.
     */
    collectionRatePct?: number | null;
    /**
     * Window end date (inclusive)
     */
    endDate: string;
    /**
     * Timestamp when the report was generated (ISO 8601)
     */
    generatedAt: string;
    /**
     * Sum of ExtInvoice.total for invoices whose finalizedAt (accrual/posting date) falls in the window; 0 when none finalized in the window
     */
    invoiced: number;
    /**
     * Window start date (inclusive)
     */
    startDate: string;
}

function isOptionalCollectionsAnalyticsReportPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CollectionsAnalyticsReportOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCollectionsAnalyticsReportPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCollectionsAnalyticsReportOptionalProperties(
    ...properties: CollectionsAnalyticsReportOptionalProperty[]
): ReadonlyArray<CollectionsAnalyticsReportOptionalProperty> {
    return properties;
}

export function instanceOfCollectionsAnalyticsReport(value: object): value is CollectionsAnalyticsReport {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCollectionsAnalyticsReportPropertyNames('applicationReversals', 'collected', 'endDate', 'generatedAt', 'invoiced', 'startDate', );
    const optionalStringProperties = createCollectionsAnalyticsReportOptionalProperties({ name: 'endDate', nullable: false }, { name: 'generatedAt', nullable: false }, { name: 'startDate', nullable: false }, );
    const optionalNumberProperties = createCollectionsAnalyticsReportOptionalProperties({ name: 'applicationReversals', nullable: false }, { name: 'collected', nullable: false }, { name: 'collectionRatePct', nullable: true }, { name: 'invoiced', nullable: false }, );
    const optionalBooleanProperties = createCollectionsAnalyticsReportOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCollectionsAnalyticsReportPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCollectionsAnalyticsReportPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCollectionsAnalyticsReportPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

