/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Review header
 */
export interface Header {
    accountCode?: string;
    accountName?: string;
    accountingPeriodCode?: string;
    /**
     * The approver (who finalized it); null until then
     */
    approver?: string;
    /**
     * The account baseline that applies to this window
     */
    baselineDate?: string;
    /**
     * Whether this window\'s statement set the baseline with its gap acknowledgement
     */
    baselineSetByThisStatement?: boolean;
    currency?: string;
    /**
     * The gap acknowledgement text of the statement that set the baseline
     */
    gapAcknowledgement?: string;
    glAccountId?: string;
    /**
     * State of the period of the statement end date: OPEN, CLOSED or HARD_LOCKED
     */
    periodState?: string;
    /**
     * The preparer (who created the reconciliation)
     */
    preparer?: string;
    reconciliationId?: string;
    /**
     * Statement provenance
     */
    sourceKind?: HeaderSourceKindEnum;
    statementEndDate?: string;
    statementId?: string;
    statementStartDate?: string;
    status?: HeaderStatusEnum;
    version?: number;
}
export enum HeaderSourceKindEnum {
    FileImport = 'FILE_IMPORT',
    ManualEntry = 'MANUAL_ENTRY',
    BankFeed = 'BANK_FEED'
};
export enum HeaderStatusEnum {
    InProgress = 'IN_PROGRESS',
    Submitted = 'SUBMITTED',
    Finalized = 'FINALIZED',
    Invalidated = 'INVALIDATED',
    Superseded = 'SUPERSEDED',
    Cancelled = 'CANCELLED'
};



function isOptionalHeaderPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type HeaderOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createHeaderPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createHeaderOptionalProperties(
    ...properties: HeaderOptionalProperty[]
): ReadonlyArray<HeaderOptionalProperty> {
    return properties;
}

export function instanceOfHeader(value: object): value is Header {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createHeaderPropertyNames();
    const optionalStringProperties = createHeaderOptionalProperties({ name: 'accountCode', nullable: false }, { name: 'accountName', nullable: false }, { name: 'accountingPeriodCode', nullable: false }, { name: 'approver', nullable: false }, { name: 'baselineDate', nullable: false }, { name: 'currency', nullable: false }, { name: 'gapAcknowledgement', nullable: false }, { name: 'glAccountId', nullable: false }, { name: 'periodState', nullable: false }, { name: 'preparer', nullable: false }, { name: 'reconciliationId', nullable: false }, { name: 'sourceKind', nullable: false }, { name: 'statementEndDate', nullable: false }, { name: 'statementId', nullable: false }, { name: 'statementStartDate', nullable: false }, { name: 'status', nullable: false }, );
    const optionalNumberProperties = createHeaderOptionalProperties({ name: 'version', nullable: false }, );
    const optionalBooleanProperties = createHeaderOptionalProperties({ name: 'baselineSetByThisStatement', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalHeaderPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalHeaderPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalHeaderPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

