/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A petty-expense category\'s tax recovery
 */
export interface InputTaxRecoveryCategory {
    /**
     * Permanent category code
     */
    code: string;
    /**
     * The category\'s label
     */
    label: string;
    /**
     * Share recovered; null when not recoverable
     */
    recoverablePercent?: number | null;
    /**
     * Whether its stated tax is recovered
     */
    taxRecoverable: boolean;
    /**
     * The setting\'s version (0 when never set), to send with a change
     */
    version: number;
}

function isOptionalInputTaxRecoveryCategoryPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type InputTaxRecoveryCategoryOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createInputTaxRecoveryCategoryPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createInputTaxRecoveryCategoryOptionalProperties(
    ...properties: InputTaxRecoveryCategoryOptionalProperty[]
): ReadonlyArray<InputTaxRecoveryCategoryOptionalProperty> {
    return properties;
}

export function instanceOfInputTaxRecoveryCategory(value: object): value is InputTaxRecoveryCategory {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createInputTaxRecoveryCategoryPropertyNames('code', 'label', 'taxRecoverable', 'version', );
    const optionalStringProperties = createInputTaxRecoveryCategoryOptionalProperties({ name: 'code', nullable: false }, { name: 'label', nullable: false }, );
    const optionalNumberProperties = createInputTaxRecoveryCategoryOptionalProperties({ name: 'recoverablePercent', nullable: true }, { name: 'version', nullable: false }, );
    const optionalBooleanProperties = createInputTaxRecoveryCategoryOptionalProperties({ name: 'taxRecoverable', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalInputTaxRecoveryCategoryPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalInputTaxRecoveryCategoryPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalInputTaxRecoveryCategoryPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

