/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Journal entry line response
 */
export interface JournalEntryLineResponse { 
    /**
     * Line UUID
     */
    lineId?: string;
    /**
     * Line sequence number
     */
    lineNumber?: number;
    /**
     * GL account UUID
     */
    glAccountId?: string;
    /**
     * GL account code
     */
    accountCode?: string;
    /**
     * GL account name
     */
    accountName?: string;
    /**
     * Debit amount
     */
    debitAmount?: number;
    /**
     * Credit amount
     */
    creditAmount?: number;
    /**
     * Line description
     */
    description?: string;
    /**
     * Optional dimensional attributes
     */
    dimensions?: { [key: string]: string; };
}

function isOptionalJournalEntryLineResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type JournalEntryLineResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createJournalEntryLineResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createJournalEntryLineResponseOptionalProperties(
    ...properties: JournalEntryLineResponseOptionalProperty[]
): ReadonlyArray<JournalEntryLineResponseOptionalProperty> {
    return properties;
}

export function instanceOfJournalEntryLineResponse(value: object): value is JournalEntryLineResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createJournalEntryLineResponsePropertyNames();
    const optionalStringProperties = createJournalEntryLineResponseOptionalProperties({ name: 'lineId', nullable: false }, { name: 'glAccountId', nullable: false }, { name: 'accountCode', nullable: false }, { name: 'accountName', nullable: false }, { name: 'description', nullable: false }, );
    const optionalNumberProperties = createJournalEntryLineResponseOptionalProperties({ name: 'lineNumber', nullable: false }, { name: 'debitAmount', nullable: false }, { name: 'creditAmount', nullable: false }, );
    const optionalBooleanProperties = createJournalEntryLineResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalJournalEntryLineResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalJournalEntryLineResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalJournalEntryLineResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

