/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to record a refund audit event
 */
export interface RefundRequest { 
    /**
     * Identifier of the invoice being refunded
     */
    invoiceId: string;
    /**
     * Identifier of the payment being refunded
     */
    paymentId: string;
    /**
     * Type of refund being recorded
     */
    refundType: RefundRequestRefundTypeEnum;
    /**
     * Amount being refunded
     */
    refundAmount: number;
    /**
     * Status of the original payment being refunded
     */
    originalPaymentStatus: RefundRequestOriginalPaymentStatusEnum;
    /**
     * Legacy client-provided actor identifier; service resolves authoritative actor from security context
     */
    actorId?: string;
    /**
     * Role of the actor performing the refund
     */
    actorRole: string;
    /**
     * Reason for the refund
     */
    reason: string;
}
export enum RefundRequestRefundTypeEnum {
    Reversal = 'REVERSAL',
    CreditMemo = 'CREDIT_MEMO',
    Adjustment = 'ADJUSTMENT'
};
export enum RefundRequestOriginalPaymentStatusEnum {
    Pending = 'PENDING',
    Settled = 'SETTLED',
    Failed = 'FAILED',
    Authorized = 'AUTHORIZED'
};



function isOptionalRefundRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type RefundRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createRefundRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createRefundRequestOptionalProperties(
    ...properties: RefundRequestOptionalProperty[]
): ReadonlyArray<RefundRequestOptionalProperty> {
    return properties;
}

export function instanceOfRefundRequest(value: object): value is RefundRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createRefundRequestPropertyNames('invoiceId', 'paymentId', 'refundType', 'refundAmount', 'originalPaymentStatus', 'actorRole', 'reason', );
    const optionalStringProperties = createRefundRequestOptionalProperties({ name: 'invoiceId', nullable: false }, { name: 'paymentId', nullable: false }, { name: 'refundType', nullable: false }, { name: 'originalPaymentStatus', nullable: false }, { name: 'actorId', nullable: false }, { name: 'actorRole', nullable: false }, { name: 'reason', nullable: false }, );
    const optionalNumberProperties = createRefundRequestOptionalProperties({ name: 'refundAmount', nullable: false }, );
    const optionalBooleanProperties = createRefundRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalRefundRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalRefundRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalRefundRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

