/**
 * POS Accounting Service API
 * Accounting service for invoice, journal entry, and GL account management
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VendorBillMatchCandidateResponse { 
    candidateId?: string;
    invoiceEventId?: string;
    vendorBillId?: string;
    vendorId?: string;
    billNumber?: string;
    billTotalAmount?: number;
    matchScore?: number;
    scoreBreakdown?: string;
    resolved?: boolean;
    selected?: boolean;
    createdAt?: string;
}

