/**
 * POS Accounting Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Vendor bill match candidate presented for manual selection during ambiguous matching
 */
export interface VendorBillMatchCandidateResponse { 
    /**
     * Candidate record identifier (used for selection)
     */
    candidateId: string;
    /**
     * Identifier of the invoice event that triggered the ambiguous match
     */
    invoiceEventId: string;
    /**
     * Identifier of the candidate vendor bill
     */
    vendorBillId: string;
    /**
     * Identifier of the vendor
     */
    vendorId?: string;
    /**
     * Bill number for display
     */
    billNumber?: string;
    /**
     * Total amount of the candidate bill
     */
    billTotalAmount?: number;
    /**
     * Composite match score (0-100)
     */
    matchScore?: number;
    /**
     * Human-readable breakdown of the match score
     */
    scoreBreakdown?: string;
    /**
     * Whether this candidate has been resolved
     */
    resolved?: boolean;
    /**
     * Whether this candidate was the selected one
     */
    selected?: boolean;
    /**
     * Timestamp when the candidate record was created (ISO 8601)
     */
    createdAt?: string;
}

function isOptionalVendorBillMatchCandidateResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type VendorBillMatchCandidateResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createVendorBillMatchCandidateResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createVendorBillMatchCandidateResponseOptionalProperties(
    ...properties: VendorBillMatchCandidateResponseOptionalProperty[]
): ReadonlyArray<VendorBillMatchCandidateResponseOptionalProperty> {
    return properties;
}

export function instanceOfVendorBillMatchCandidateResponse(value: object): value is VendorBillMatchCandidateResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createVendorBillMatchCandidateResponsePropertyNames('candidateId', 'invoiceEventId', 'vendorBillId', );
    const optionalStringProperties = createVendorBillMatchCandidateResponseOptionalProperties({ name: 'candidateId', nullable: false }, { name: 'invoiceEventId', nullable: false }, { name: 'vendorBillId', nullable: false }, { name: 'vendorId', nullable: false }, { name: 'billNumber', nullable: false }, { name: 'scoreBreakdown', nullable: false }, );
    const optionalNumberProperties = createVendorBillMatchCandidateResponseOptionalProperties({ name: 'billTotalAmount', nullable: false }, { name: 'matchScore', nullable: false }, );
    const optionalBooleanProperties = createVendorBillMatchCandidateResponseOptionalProperties({ name: 'resolved', nullable: false }, { name: 'selected', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalVendorBillMatchCandidateResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalVendorBillMatchCandidateResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalVendorBillMatchCandidateResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

