/**
 * Supplier API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One PRICE_CATALOG binding\'s schedule and scheduler-lease state.
 */
export interface PriceCatalogBindingFreshness { 
    /**
     * The endpoint binding.
     */
    bindingId?: string;
    /**
     * End of the last window the schedule coordinator checkpointed. Null for full-snapshot protocols — every current PRICAT protocol — and for bindings a scheduled run has never claimed.
     */
    checkpointAt?: string;
    /**
     * Whether the binding is enabled.
     */
    enabled?: boolean;
    /**
     * How the last scheduled run ended; null when a scheduled run never ran.
     */
    lastRunOutcome?: string;
    /**
     * When the last scheduled run started; null when a scheduled run never ran.
     */
    lastRunStartedAt?: string;
    /**
     * The binding\'s schedule cron; null when the feed only runs on demand.
     */
    scheduleCron?: string;
}

function isOptionalPriceCatalogBindingFreshnessPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type PriceCatalogBindingFreshnessOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createPriceCatalogBindingFreshnessPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createPriceCatalogBindingFreshnessOptionalProperties(
    ...properties: PriceCatalogBindingFreshnessOptionalProperty[]
): ReadonlyArray<PriceCatalogBindingFreshnessOptionalProperty> {
    return properties;
}

export function instanceOfPriceCatalogBindingFreshness(value: object): value is PriceCatalogBindingFreshness {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createPriceCatalogBindingFreshnessPropertyNames();
    const optionalStringProperties = createPriceCatalogBindingFreshnessOptionalProperties({ name: 'bindingId', nullable: false }, { name: 'checkpointAt', nullable: false }, { name: 'lastRunOutcome', nullable: false }, { name: 'lastRunStartedAt', nullable: false }, { name: 'scheduleCron', nullable: false }, );
    const optionalNumberProperties = createPriceCatalogBindingFreshnessOptionalProperties();
    const optionalBooleanProperties = createPriceCatalogBindingFreshnessOptionalProperties({ name: 'enabled', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalPriceCatalogBindingFreshnessPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalPriceCatalogBindingFreshnessPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalPriceCatalogBindingFreshnessPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

