/**
 * Supplier API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One inquired article. Named explicitly because an unqualified \"Line\" collides with other modules\' schemas of the same name when specs are merged for SDK generation.
 */
export interface StockInquiryRequestLine { 
    articleEan?: string;
    requestedQuantity?: number;
    supplierArticleCode?: string;
}

function isOptionalStockInquiryRequestLinePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type StockInquiryRequestLineOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createStockInquiryRequestLinePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createStockInquiryRequestLineOptionalProperties(
    ...properties: StockInquiryRequestLineOptionalProperty[]
): ReadonlyArray<StockInquiryRequestLineOptionalProperty> {
    return properties;
}

export function instanceOfStockInquiryRequestLine(value: object): value is StockInquiryRequestLine {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createStockInquiryRequestLinePropertyNames();
    const optionalStringProperties = createStockInquiryRequestLineOptionalProperties({ name: 'articleEan', nullable: false }, { name: 'supplierArticleCode', nullable: false }, );
    const optionalNumberProperties = createStockInquiryRequestLineOptionalProperties({ name: 'requestedQuantity', nullable: false }, );
    const optionalBooleanProperties = createStockInquiryRequestLineOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalStockInquiryRequestLinePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalStockInquiryRequestLinePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalStockInquiryRequestLinePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

