/**
 * Vehicle Inventory API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Vehicle care preferences record
 */
export interface VehicleCarePreferenceResponse {
    /**
     * Timestamp when the preference record was created
     */
    createdAt: string;
    /**
     * User identifier that created the preference record
     */
    createdByUserId?: string;
    /**
     * Unique identifier of the preference record
     */
    id: string;
    /**
     * Preferences payload stored as flexible key/value JSON
     */
    preferences: object;
    /**
     * Structured service interval in whole months; null means use the CRM default (#1175)
     */
    serviceIntervalMonths?: number;
    /**
     * Service notes for technicians
     */
    serviceNotes?: string;
    /**
     * Timestamp when the preference record was last updated
     */
    updatedAt: string;
    /**
     * User identifier that last updated the preference record
     */
    updatedByUserId?: string;
    /**
     * Identifier of the vehicle the preferences apply to
     */
    vehicleId: string;
    /**
     * Optimistic-locking version of the preference record
     */
    version: number;
}

function isOptionalVehicleCarePreferenceResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type VehicleCarePreferenceResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createVehicleCarePreferenceResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createVehicleCarePreferenceResponseOptionalProperties(
    ...properties: VehicleCarePreferenceResponseOptionalProperty[]
): ReadonlyArray<VehicleCarePreferenceResponseOptionalProperty> {
    return properties;
}

export function instanceOfVehicleCarePreferenceResponse(value: object): value is VehicleCarePreferenceResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createVehicleCarePreferenceResponsePropertyNames('createdAt', 'id', 'preferences', 'updatedAt', 'vehicleId', 'version', );
    const optionalStringProperties = createVehicleCarePreferenceResponseOptionalProperties({ name: 'createdAt', nullable: false }, { name: 'createdByUserId', nullable: false }, { name: 'id', nullable: false }, { name: 'serviceNotes', nullable: false }, { name: 'updatedAt', nullable: false }, { name: 'updatedByUserId', nullable: false }, { name: 'vehicleId', nullable: false }, );
    const optionalNumberProperties = createVehicleCarePreferenceResponseOptionalProperties({ name: 'serviceIntervalMonths', nullable: false }, { name: 'version', nullable: false }, );
    const optionalBooleanProperties = createVehicleCarePreferenceResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalVehicleCarePreferenceResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalVehicleCarePreferenceResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalVehicleCarePreferenceResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

