/**
 * Vehicle Inventory API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Vehicle object to be created
 */
export interface VehicleLegacyRequest { 
    id?: string;
    make?: string;
    model?: string;
    year?: number;
    vin?: string;
    vehicleType?: string;
}

function isOptionalVehicleLegacyRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type VehicleLegacyRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createVehicleLegacyRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createVehicleLegacyRequestOptionalProperties(
    ...properties: VehicleLegacyRequestOptionalProperty[]
): ReadonlyArray<VehicleLegacyRequestOptionalProperty> {
    return properties;
}

export function instanceOfVehicleLegacyRequest(value: object): value is VehicleLegacyRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createVehicleLegacyRequestPropertyNames();
    const optionalStringProperties = createVehicleLegacyRequestOptionalProperties({ name: 'id', nullable: false }, { name: 'make', nullable: false }, { name: 'model', nullable: false }, { name: 'vin', nullable: false }, { name: 'vehicleType', nullable: false }, );
    const optionalNumberProperties = createVehicleLegacyRequestOptionalProperties({ name: 'year', nullable: false }, );
    const optionalBooleanProperties = createVehicleLegacyRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalVehicleLegacyRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalVehicleLegacyRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalVehicleLegacyRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

