/**
 * POS Tax Service API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tax breakdown for a single line item
 */
export interface LineItemTax { 
    /**
     * Line item identifier
     */
    lineItemId: string;
    /**
     * Line subtotal before tax
     */
    subtotal: number;
    /**
     * Line tax amount
     */
    taxAmount: number;
    /**
     * Line total including tax
     */
    total: number;
    /**
     * Whether this line item is tax exempt
     */
    taxExempt?: boolean;
}

