/**
 * POS Tax Service API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One box of an information-return form
 */
export interface TaxInformationReturnBox {
    /**
     * Box code
     */
    box: string;
    /**
     * Box label
     */
    label: string;
}

function isOptionalTaxInformationReturnBoxPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type TaxInformationReturnBoxOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createTaxInformationReturnBoxPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createTaxInformationReturnBoxOptionalProperties(
    ...properties: TaxInformationReturnBoxOptionalProperty[]
): ReadonlyArray<TaxInformationReturnBoxOptionalProperty> {
    return properties;
}

export function instanceOfTaxInformationReturnBox(value: object): value is TaxInformationReturnBox {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createTaxInformationReturnBoxPropertyNames('box', 'label', );
    const optionalStringProperties = createTaxInformationReturnBoxOptionalProperties({ name: 'box', nullable: false }, { name: 'label', nullable: false }, );
    const optionalNumberProperties = createTaxInformationReturnBoxOptionalProperties();
    const optionalBooleanProperties = createTaxInformationReturnBoxOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalTaxInformationReturnBoxPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalTaxInformationReturnBoxPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalTaxInformationReturnBoxPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

