/**
 * POS Invoice API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to generate a receipt for an invoice payment
 */
export interface GenerateReceiptRequest { 
    /**
     * Payment intent the receipt is generated for
     */
    paymentIntentId: string;
    /**
     * Identifier of the terminal producing the receipt
     */
    terminalId: string;
    /**
     * Receipt template identifier
     */
    templateId: string;
    /**
     * Receipt template version
     */
    templateVersion: string;
}

function isOptionalGenerateReceiptRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type GenerateReceiptRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createGenerateReceiptRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createGenerateReceiptRequestOptionalProperties(
    ...properties: GenerateReceiptRequestOptionalProperty[]
): ReadonlyArray<GenerateReceiptRequestOptionalProperty> {
    return properties;
}

export function instanceOfGenerateReceiptRequest(value: object): value is GenerateReceiptRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createGenerateReceiptRequestPropertyNames('paymentIntentId', 'terminalId', 'templateId', 'templateVersion', );
    const optionalStringProperties = createGenerateReceiptRequestOptionalProperties({ name: 'paymentIntentId', nullable: false }, { name: 'terminalId', nullable: false }, { name: 'templateId', nullable: false }, { name: 'templateVersion', nullable: false }, );
    const optionalNumberProperties = createGenerateReceiptRequestOptionalProperties();
    const optionalBooleanProperties = createGenerateReceiptRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalGenerateReceiptRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalGenerateReceiptRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalGenerateReceiptRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

