/**
 * POS Invoice API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response payload returned after invoice generation.
 */
export interface InvoiceGenerationResponse { 
    /**
     * Generated invoice identifier.
     */
    invoiceId?: string;
    /**
     * Invoice status.
     */
    status?: string;
    /**
     * Source workorder identifier.
     */
    workorderId?: string;
    /**
     * Source estimate identifier.
     */
    estimateId?: string;
    /**
     * Approval identifier used for generation.
     */
    approvalId?: string;
    /**
     * Subtotal amount before tax.
     */
    subtotal?: number;
    /**
     * Tax amount.
     */
    taxAmount?: number;
    /**
     * Total amount after tax.
     */
    totalAmount?: number;
    /**
     * Creation timestamp (UTC).
     */
    createdAt?: string;
}

