/**
 * POS Invoice API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sales order line for invoice creation.
 */
export interface OrderInvoiceLineItem { 
    /**
     * Extended line amount (post-line-discount, pre-tax).
     */
    amount: number;
    /**
     * Line description as sold.
     */
    description: string;
    /**
     * Sales order line identifier, carried for settlement reconciliation.
     */
    orderLineId?: string;
    /**
     * Quantity sold.
     */
    quantity: number;
    /**
     * Per-line tax amount.
     */
    taxAmount?: number;
    /**
     * Line item type (e.g. PART, LABOR, FEE).
     */
    type?: string;
    /**
     * Applied unit price.
     */
    unitPrice: number;
}

function isOptionalOrderInvoiceLineItemPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type OrderInvoiceLineItemOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createOrderInvoiceLineItemPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createOrderInvoiceLineItemOptionalProperties(
    ...properties: OrderInvoiceLineItemOptionalProperty[]
): ReadonlyArray<OrderInvoiceLineItemOptionalProperty> {
    return properties;
}

export function instanceOfOrderInvoiceLineItem(value: object): value is OrderInvoiceLineItem {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createOrderInvoiceLineItemPropertyNames('amount', 'description', 'quantity', 'unitPrice', );
    const optionalStringProperties = createOrderInvoiceLineItemOptionalProperties({ name: 'description', nullable: false }, { name: 'orderLineId', nullable: false }, { name: 'type', nullable: false }, );
    const optionalNumberProperties = createOrderInvoiceLineItemOptionalProperties({ name: 'amount', nullable: false }, { name: 'quantity', nullable: false }, { name: 'taxAmount', nullable: false }, { name: 'unitPrice', nullable: false }, );
    const optionalBooleanProperties = createOrderInvoiceLineItemOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalOrderInvoiceLineItemPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalOrderInvoiceLineItemPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalOrderInvoiceLineItemPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

