/**
 * POS Invoice API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefundPaymentRequest { 
    amount: number;
    reason: RefundPaymentRequestReasonEnum;
    notes?: string;
}
export enum RefundPaymentRequestReasonEnum {
    CustomerReturn = 'CUSTOMER_RETURN',
    ServiceError = 'SERVICE_ERROR',
    Overcharge = 'OVERCHARGE',
    DamagedGoods = 'DAMAGED_GOODS',
    Goodwill = 'GOODWILL',
    ChargebackAvoidance = 'CHARGEBACK_AVOIDANCE',
    FraudPrevention = 'FRAUD_PREVENTION',
    ManagerDiscretion = 'MANAGER_DISCRETION',
    Other = 'OTHER'
};



