/**
 * POS Invoice API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to record a standalone refund against an invoice
 */
export interface StandaloneRefundRequest { 
    /**
     * Amount to refund
     */
    amount: number;
    /**
     * Reason the refund is being issued
     */
    reason: StandaloneRefundRequestReasonEnum;
    /**
     * Optional free-text notes explaining the refund
     */
    notes?: string;
    /**
     * Optional correlation id to an external record (e.g. a warranty claim settlement)
     */
    externalReference?: string;
}
export enum StandaloneRefundRequestReasonEnum {
    CustomerReturn = 'CUSTOMER_RETURN',
    ServiceError = 'SERVICE_ERROR',
    Overcharge = 'OVERCHARGE',
    DamagedGoods = 'DAMAGED_GOODS',
    Goodwill = 'GOODWILL',
    ChargebackAvoidance = 'CHARGEBACK_AVOIDANCE',
    FraudPrevention = 'FRAUD_PREVENTION',
    ManagerDiscretion = 'MANAGER_DISCRETION',
    Other = 'OTHER'
};



function isOptionalStandaloneRefundRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type StandaloneRefundRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createStandaloneRefundRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createStandaloneRefundRequestOptionalProperties(
    ...properties: StandaloneRefundRequestOptionalProperty[]
): ReadonlyArray<StandaloneRefundRequestOptionalProperty> {
    return properties;
}

export function instanceOfStandaloneRefundRequest(value: object): value is StandaloneRefundRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createStandaloneRefundRequestPropertyNames('amount', 'reason', );
    const optionalStringProperties = createStandaloneRefundRequestOptionalProperties({ name: 'reason', nullable: false }, { name: 'notes', nullable: false }, { name: 'externalReference', nullable: false }, );
    const optionalNumberProperties = createStandaloneRefundRequestOptionalProperties({ name: 'amount', nullable: false }, );
    const optionalBooleanProperties = createStandaloneRefundRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalStandaloneRefundRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalStandaloneRefundRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalStandaloneRefundRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

