/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Approval details including user ID and note
 */
export interface ApproveChangeRequestDTO { 
    /**
     * Deprecated. Actor identity is resolved from authenticated security context.
     */
    approvedBy?: string;
    /**
     * Approval note captured as the decision artifact
     */
    approvalNote: string;
}

