/**
 * POS Workorder Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload to issue authorized part quantity to a workorder
 */
export interface IssuePartRequest { 
    /**
     * Workorder part identifier
     */
    workorderPartId: string;
    /**
     * Quantity to issue
     */
    quantity: number;
    /**
     * Optional issue notes
     */
    notes?: string;
}

export function instanceOfIssuePartRequest(value: object): value is IssuePartRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
    const _v = value as Record<string, unknown>;
    if (!('workorderPartId' in _v) || _v['workorderPartId'] === undefined) return false;
    if ('workorderPartId' in _v && typeof _v['workorderPartId'] !== 'string') return false;
    if (!('quantity' in _v) || _v['quantity'] === undefined) return false;
    if ('quantity' in _v && typeof _v['quantity'] !== 'number') return false;
    if ('notes' in _v && typeof _v['notes'] !== 'string') return false;
    return true;
}

