/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Approval or rejection status for a specific line item
 */
export interface LineItemApprovalDto { 
    /**
     * ID of the line item (service/product) being approved or rejected
     */
    lineItemId: string;
    /**
     * Whether this line item is approved (true) or rejected (false)
     */
    approved: boolean;
    /**
     * Reason for rejection (required if approved=false)
     */
    rejectionReason?: string;
    /**
     * Additional notes about this line item decision
     */
    notes?: string;
}

