/**
 * POS Workorder Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Optional request payload used when starting a workorder
 */
export interface StartWorkorderRequest { 
    /**
     * Deprecated. Actor identity is resolved from authenticated security context.
     * @deprecated
     */
    userId?: string;
    /**
     * Optional reason associated with start transition
     */
    reason?: string;
}

function isOptionalStartWorkorderRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type StartWorkorderRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createStartWorkorderRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createStartWorkorderRequestOptionalProperties(
    ...properties: StartWorkorderRequestOptionalProperty[]
): ReadonlyArray<StartWorkorderRequestOptionalProperty> {
    return properties;
}

export function instanceOfStartWorkorderRequest(value: object): value is StartWorkorderRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createStartWorkorderRequestPropertyNames();
    const optionalStringProperties = createStartWorkorderRequestOptionalProperties({ name: 'userId', nullable: false }, { name: 'reason', nullable: false }, );
    const optionalNumberProperties = createStartWorkorderRequestOptionalProperties();
    const optionalBooleanProperties = createStartWorkorderRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalStartWorkorderRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalStartWorkorderRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalStartWorkorderRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

