/**
 * POS Workorder Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Work order state transition history entry
 */
export interface WorkorderStateTransitionResponse { 
    /**
     * Unique identifier for this transition record
     */
    id?: string;
    /**
     * ID of the work order
     */
    workorderId?: string;
    /**
     * The status the work order transitioned FROM
     */
    fromStatus?: string;
    /**
     * The status the work order transitioned TO
     */
    toStatus?: string;
    /**
     * Timestamp when the transition occurred
     */
    transitionedAt?: string;
    /**
     * Stable actor identifier who performed the transition
     */
    transitionedBy?: string;
    /**
     * Reason for the transition
     */
    reason?: string;
    /**
     * Additional metadata about the transition
     */
    metadata?: string;
}

