/**
 * POS Workorder Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Workorder id resolved to its human workorder number
 */
export interface WorkorderNumberRef { 
    /**
     * Workorder identifier
     */
    workorderId: string;
    /**
     * Human workorder number
     */
    workorderNumber?: string;
}

function isOptionalWorkorderNumberRefPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type WorkorderNumberRefOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createWorkorderNumberRefPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createWorkorderNumberRefOptionalProperties(
    ...properties: WorkorderNumberRefOptionalProperty[]
): ReadonlyArray<WorkorderNumberRefOptionalProperty> {
    return properties;
}

export function instanceOfWorkorderNumberRef(value: object): value is WorkorderNumberRef {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createWorkorderNumberRefPropertyNames('workorderId', );
    const optionalStringProperties = createWorkorderNumberRefOptionalProperties({ name: 'workorderId', nullable: false }, { name: 'workorderNumber', nullable: false }, );
    const optionalNumberProperties = createWorkorderNumberRefOptionalProperties();
    const optionalBooleanProperties = createWorkorderNumberRefOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalWorkorderNumberRefPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalWorkorderNumberRefPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalWorkorderNumberRefPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

