/**
 * POS Workorder Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Labor entry response
 */
export interface WorkorderLaborEntryResponse { 
    /**
     * Unique ID of the labor entry
     */
    id?: string;
    /**
     * Workorder ID
     */
    workorderId?: string;
    /**
     * Service line item ID
     */
    workorderServiceId?: string;
    /**
     * Technician ID who performed the work
     */
    technicianId?: string;
    /**
     * Labor session start time
     */
    startTime?: string;
    /**
     * Labor session end time (null if still active)
     */
    endTime?: string;
    /**
     * Hours worked
     */
    hoursWorked?: number;
    /**
     * Session notes
     */
    notes?: string;
    /**
     * Adjustment reason (if hours were manually adjusted)
     */
    adjustmentReason?: string;
    /**
     * Whether this session is still active (not stopped)
     */
    active?: boolean;
    /**
     * User who created this entry
     */
    createdBy?: string;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}

export function instanceOfWorkorderLaborEntryResponse(value: object): value is WorkorderLaborEntryResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
    const _v = value as Record<string, unknown>;
    if ('id' in _v && typeof _v['id'] !== 'string') return false;
    if ('workorderId' in _v && typeof _v['workorderId'] !== 'string') return false;
    if ('workorderServiceId' in _v && typeof _v['workorderServiceId'] !== 'string') return false;
    if ('technicianId' in _v && typeof _v['technicianId'] !== 'string') return false;
    if ('hoursWorked' in _v && typeof _v['hoursWorked'] !== 'number') return false;
    if ('notes' in _v && typeof _v['notes'] !== 'string') return false;
    if ('adjustmentReason' in _v && typeof _v['adjustmentReason'] !== 'string') return false;
    if ('active' in _v && typeof _v['active'] !== 'boolean') return false;
    if ('createdBy' in _v && typeof _v['createdBy'] !== 'string') return false;
    return true;
}

