/**
 * POS Workorder Service API
 * Workorder service for managing workorders and tasks
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Labor entry response
 */
export interface WorkorderLaborEntryResponse { 
    /**
     * Unique ID of the labor entry
     */
    id?: string;
    /**
     * Workorder ID
     */
    workorderId?: string;
    /**
     * Service line item ID
     */
    workorderServiceId?: string;
    /**
     * Technician ID who performed the work
     */
    technicianId?: string;
    /**
     * Labor session start time
     */
    startTime?: string;
    /**
     * Labor session end time (null if still active)
     */
    endTime?: string;
    /**
     * Hours worked
     */
    hoursWorked?: number;
    /**
     * Session notes
     */
    notes?: string;
    /**
     * Adjustment reason (if hours were manually adjusted)
     */
    adjustmentReason?: string;
    /**
     * Whether this session is still active (not stopped)
     */
    active?: boolean;
    /**
     * User who created this entry
     */
    createdBy?: string;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}

