export * from './approvalConfigurationAPI.service';
import { ApprovalConfigurationAPIService } from './approvalConfigurationAPI.service';
export * from './changeRequestAPI.service';
import { ChangeRequestAPIService } from './changeRequestAPI.service';
export * from './dailyDispatchBoardDashboard.service';
import { DailyDispatchBoardDashboardService } from './dailyDispatchBoardDashboard.service';
export * from './estimateAPI.service';
import { EstimateAPIService } from './estimateAPI.service';
export * from './estimateSearch.service';
import { EstimateSearchService } from './estimateSearch.service';
export * from './estimatesFromAppointments.service';
import { EstimatesFromAppointmentsService } from './estimatesFromAppointments.service';
export * from './operationalContext.service';
import { OperationalContextService } from './operationalContext.service';
export * from './substituteLinkAPI.service';
import { SubstituteLinkAPIService } from './substituteLinkAPI.service';
export * from './technicianAssignmentAPI.service';
import { TechnicianAssignmentAPIService } from './technicianAssignmentAPI.service';
export * from './timeEntryAPI.service';
import { TimeEntryAPIService } from './timeEntryAPI.service';
export * from './travelSegmentAPI.service';
import { TravelSegmentAPIService } from './travelSegmentAPI.service';
export * from './wIPDashboard.service';
import { WIPDashboardService } from './wIPDashboard.service';
export * from './workOrderAPI.service';
import { WorkOrderAPIService } from './workOrderAPI.service';
export * from './workSessionAPI.service';
import { WorkSessionAPIService } from './workSessionAPI.service';
export * from './workexecTimeTrackingAPI.service';
import { WorkexecTimeTrackingAPIService } from './workexecTimeTrackingAPI.service';
export * from './workorderDetail.service';
import { WorkorderDetailService } from './workorderDetail.service';
export * from './workorderLaborAPI.service';
import { WorkorderLaborAPIService } from './workorderLaborAPI.service';
export * from './workorderPartAdjustments.service';
import { WorkorderPartAdjustmentsService } from './workorderPartAdjustments.service';
export * from './workorderPartsUsage.service';
import { WorkorderPartsUsageService } from './workorderPartsUsage.service';
export * from './workorderPickFacade.service';
import { WorkorderPickFacadeService } from './workorderPickFacade.service';
export * from './workorderPickedItems.service';
import { WorkorderPickedItemsService } from './workorderPickedItems.service';
export const APIS = [ApprovalConfigurationAPIService, ChangeRequestAPIService, DailyDispatchBoardDashboardService, EstimateAPIService, EstimateSearchService, EstimatesFromAppointmentsService, OperationalContextService, SubstituteLinkAPIService, TechnicianAssignmentAPIService, TimeEntryAPIService, TravelSegmentAPIService, WIPDashboardService, WorkOrderAPIService, WorkSessionAPIService, WorkexecTimeTrackingAPIService, WorkorderDetailService, WorkorderLaborAPIService, WorkorderPartAdjustmentsService, WorkorderPartsUsageService, WorkorderPickFacadeService, WorkorderPickedItemsService];
