/**
 * Marketing API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A channel-specific message template
 */
export interface MessageTemplateResponse {
    /**
     * Audience whose token vocabulary applies
     */
    audienceType: MessageTemplateResponseAudienceTypeEnum;
    /**
     * Tokens available to this template\'s audience
     */
    availableTokens: Set<string>;
    /**
     * Message body with token placeholders
     */
    body: string;
    /**
     * Delivery channel
     */
    channel: MessageTemplateResponseChannelEnum;
    /**
     * Creation timestamp
     */
    createdAt?: string;
    /**
     * Template name
     */
    name: string;
    /**
     * Subject line; null for SMS
     */
    subject?: string;
    /**
     * Template identifier
     */
    templateId: string;
    /**
     * Last update timestamp
     */
    updatedAt?: string;
}
export enum MessageTemplateResponseAudienceTypeEnum {
    Commercial = 'COMMERCIAL',
    Individual = 'INDIVIDUAL'
};
export enum MessageTemplateResponseChannelEnum {
    Email = 'EMAIL',
    Sms = 'SMS'
};



function isOptionalMessageTemplateResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type MessageTemplateResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createMessageTemplateResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createMessageTemplateResponseOptionalProperties(
    ...properties: MessageTemplateResponseOptionalProperty[]
): ReadonlyArray<MessageTemplateResponseOptionalProperty> {
    return properties;
}

export function instanceOfMessageTemplateResponse(value: object): value is MessageTemplateResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createMessageTemplateResponsePropertyNames('audienceType', 'availableTokens', 'body', 'channel', 'name', 'templateId', );
    const optionalStringProperties = createMessageTemplateResponseOptionalProperties({ name: 'audienceType', nullable: false }, { name: 'body', nullable: false }, { name: 'channel', nullable: false }, { name: 'createdAt', nullable: false }, { name: 'name', nullable: false }, { name: 'subject', nullable: false }, { name: 'templateId', nullable: false }, { name: 'updatedAt', nullable: false }, );
    const optionalNumberProperties = createMessageTemplateResponseOptionalProperties();
    const optionalBooleanProperties = createMessageTemplateResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalMessageTemplateResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalMessageTemplateResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalMessageTemplateResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

