export * from './aSN.service';
import { ASNService } from './aSN.service';
export * from './consumption.service';
import { ConsumptionService } from './consumption.service';
export * from './cycleCountAPI.service';
import { CycleCountAPIService } from './cycleCountAPI.service';
export * from './cycleCountAdjustments.service';
import { CycleCountAdjustmentsService } from './cycleCountAdjustments.service';
export * from './cycleCountOperations.service';
import { CycleCountOperationsService } from './cycleCountOperations.service';
export * from './cycleCountPlans.service';
import { CycleCountPlansService } from './cycleCountPlans.service';
export * from './cycleCountQuery.service';
import { CycleCountQueryService } from './cycleCountQuery.service';
export * from './inventoryAvailability.service';
import { InventoryAvailabilityService } from './inventoryAvailability.service';
export * from './inventoryBulkIngestAPI.service';
import { InventoryBulkIngestAPIService } from './inventoryBulkIngestAPI.service';
export * from './inventoryLedger.service';
import { InventoryLedgerService } from './inventoryLedger.service';
export * from './inventoryLocations.service';
import { InventoryLocationsService } from './inventoryLocations.service';
export * from './inventoryManagement.service';
import { InventoryManagementService } from './inventoryManagement.service';
export * from './inventoryReferenceData.service';
import { InventoryReferenceDataService } from './inventoryReferenceData.service';
export * from './inventoryReservations.service';
import { InventoryReservationsService } from './inventoryReservations.service';
export * from './inventorySites.service';
import { InventorySitesService } from './inventorySites.service';
export * from './pickLists.service';
import { PickListsService } from './pickLists.service';
export * from './pickingLists.service';
import { PickingListsService } from './pickingLists.service';
export * from './purchaseOrders.service';
import { PurchaseOrdersService } from './purchaseOrders.service';
export * from './putaway.service';
import { PutawayService } from './putaway.service';
export * from './putawayExecution.service';
import { PutawayExecutionService } from './putawayExecution.service';
export * from './reallocation.service';
import { ReallocationService } from './reallocation.service';
export * from './receiving.service';
import { ReceivingService } from './receiving.service';
export * from './replenishment.service';
import { ReplenishmentService } from './replenishment.service';
export * from './returns.service';
import { ReturnsService } from './returns.service';
export * from './shortageResolution.service';
import { ShortageResolutionService } from './shortageResolution.service';
export * from './stockMovements.service';
import { StockMovementsService } from './stockMovements.service';
export const APIS = [ASNService, ConsumptionService, CycleCountAPIService, CycleCountAdjustmentsService, CycleCountOperationsService, CycleCountPlansService, CycleCountQueryService, InventoryAvailabilityService, InventoryBulkIngestAPIService, InventoryLedgerService, InventoryLocationsService, InventoryManagementService, InventoryReferenceDataService, InventoryReservationsService, InventorySitesService, PickListsService, PickingListsService, PurchaseOrdersService, PutawayService, PutawayExecutionService, ReallocationService, ReceivingService, ReplenishmentService, ReturnsService, ShortageResolutionService, StockMovementsService];
