export * from './aSN.service';
import { ASNService } from './aSN.service';
export * from './backorders.service';
import { BackordersService } from './backorders.service';
export * from './consumption.service';
import { ConsumptionService } from './consumption.service';
export * from './cycleCountAPI.service';
import { CycleCountAPIService } from './cycleCountAPI.service';
export * from './cycleCountAdjustments.service';
import { CycleCountAdjustmentsService } from './cycleCountAdjustments.service';
export * from './cycleCountOperations.service';
import { CycleCountOperationsService } from './cycleCountOperations.service';
export * from './cycleCountPlans.service';
import { CycleCountPlansService } from './cycleCountPlans.service';
export * from './cycleCountQuery.service';
import { CycleCountQueryService } from './cycleCountQuery.service';
export * from './cycleCountSchedules.service';
import { CycleCountSchedulesService } from './cycleCountSchedules.service';
export * from './inventoryAvailability.service';
import { InventoryAvailabilityService } from './inventoryAvailability.service';
export * from './inventoryBulkIngestAPI.service';
import { InventoryBulkIngestAPIService } from './inventoryBulkIngestAPI.service';
export * from './inventoryLedger.service';
import { InventoryLedgerService } from './inventoryLedger.service';
export * from './inventoryLocations.service';
import { InventoryLocationsService } from './inventoryLocations.service';
export * from './inventoryManagement.service';
import { InventoryManagementService } from './inventoryManagement.service';
export * from './inventoryReferenceData.service';
import { InventoryReferenceDataService } from './inventoryReferenceData.service';
export * from './inventoryReservations.service';
import { InventoryReservationsService } from './inventoryReservations.service';
export * from './inventoryRevaluation.service';
import { InventoryRevaluationService } from './inventoryRevaluation.service';
export * from './inventoryRollup.service';
import { InventoryRollupService } from './inventoryRollup.service';
export * from './inventorySites.service';
import { InventorySitesService } from './inventorySites.service';
export * from './inventoryValuation.service';
import { InventoryValuationService } from './inventoryValuation.service';
export * from './locationSync.service';
import { LocationSyncService } from './locationSync.service';
export * from './lots.service';
import { LotsService } from './lots.service';
export * from './pickLists.service';
import { PickListsService } from './pickLists.service';
export * from './pickingLists.service';
import { PickingListsService } from './pickingLists.service';
export * from './purchaseOrders.service';
import { PurchaseOrdersService } from './purchaseOrders.service';
export * from './purchaseSuggestions.service';
import { PurchaseSuggestionsService } from './purchaseSuggestions.service';
export * from './putaway.service';
import { PutawayService } from './putaway.service';
export * from './putawayExecution.service';
import { PutawayExecutionService } from './putawayExecution.service';
export * from './reallocation.service';
import { ReallocationService } from './reallocation.service';
export * from './receiving.service';
import { ReceivingService } from './receiving.service';
export * from './replenishment.service';
import { ReplenishmentService } from './replenishment.service';
export * from './returns.service';
import { ReturnsService } from './returns.service';
export * from './scraps.service';
import { ScrapsService } from './scraps.service';
export * from './serialUnits.service';
import { SerialUnitsService } from './serialUnits.service';
export * from './shortageResolution.service';
import { ShortageResolutionService } from './shortageResolution.service';
export * from './sourcingStrategies.service';
import { SourcingStrategiesService } from './sourcingStrategies.service';
export * from './stockMovements.service';
import { StockMovementsService } from './stockMovements.service';
export * from './traceability.service';
import { TraceabilityService } from './traceability.service';
export * from './transferOrders.service';
import { TransferOrdersService } from './transferOrders.service';
export * from './valuationMethods.service';
import { ValuationMethodsService } from './valuationMethods.service';
export const APIS = [ASNService, BackordersService, ConsumptionService, CycleCountAPIService, CycleCountAdjustmentsService, CycleCountOperationsService, CycleCountPlansService, CycleCountQueryService, CycleCountSchedulesService, InventoryAvailabilityService, InventoryBulkIngestAPIService, InventoryLedgerService, InventoryLocationsService, InventoryManagementService, InventoryReferenceDataService, InventoryReservationsService, InventoryRevaluationService, InventoryRollupService, InventorySitesService, InventoryValuationService, LocationSyncService, LotsService, PickListsService, PickingListsService, PurchaseOrdersService, PurchaseSuggestionsService, PutawayService, PutawayExecutionService, ReallocationService, ReceivingService, ReplenishmentService, ReturnsService, ScrapsService, SerialUnitsService, ShortageResolutionService, SourcingStrategiesService, StockMovementsService, TraceabilityService, TransferOrdersService, ValuationMethodsService];
