/**
 * POS Shop Manager Service API
 * Shop Manager service for managing shop operations and staff
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConflictDetails } from './conflictDetails';


export interface ScheduleEventView { 
    eventId?: string;
    eventType?: string;
    subType?: string;
    startTime?: string;
    endTime?: string;
    title?: string;
    hasConflict?: boolean;
    severity?: string;
    conflictDetails?: ConflictDetails;
}

