/**
 * POS Shop Manager Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleEventView } from './scheduleEventView';


export interface ScheduleResourceView { 
    resourceId?: string;
    resourceType?: string;
    resourceName?: string;
    events?: Array<ScheduleEventView>;
}

function isOptionalScheduleResourceViewPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type ScheduleResourceViewOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createScheduleResourceViewPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createScheduleResourceViewOptionalProperties(
    ...properties: ScheduleResourceViewOptionalProperty[]
): ReadonlyArray<ScheduleResourceViewOptionalProperty> {
    return properties;
}

export function instanceOfScheduleResourceView(value: object): value is ScheduleResourceView {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createScheduleResourceViewPropertyNames();
    const optionalStringProperties = createScheduleResourceViewOptionalProperties({ name: 'resourceId', nullable: false }, { name: 'resourceType', nullable: false }, { name: 'resourceName', nullable: false }, );
    const optionalNumberProperties = createScheduleResourceViewOptionalProperties();
    const optionalBooleanProperties = createScheduleResourceViewOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalScheduleResourceViewPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalScheduleResourceViewPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalScheduleResourceViewPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

