/**
 * POS Shop Manager Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Filter criteria for querying the shop audit trail. At least one field must be non-null.
 */
export interface ShopAuditFilter { 
    /**
     * Workorder UUID to filter by - one word per workspace naming policy
     */
    workorderId?: string;
    /**
     * Appointment UUID to filter by
     */
    appointmentId?: string;
    /**
     * Mechanic user ID to filter by
     */
    mechanicId?: string;
    /**
     * Actor user ID to filter by
     */
    actorUserId?: string;
    /**
     * Specific audit event type to filter by
     */
    eventType?: ShopAuditFilterEventTypeEnum;
    /**
     * Location ID to filter by
     */
    locationId?: string;
    /**
     * Inclusive start timestamp for date-time range filter
     */
    fromDateTime?: string;
    /**
     * Inclusive end timestamp for date-time range filter
     */
    toDateTime?: string;
}
export enum ShopAuditFilterEventTypeEnum {
    ScheduleCreated = 'SCHEDULE_CREATED',
    ScheduleUpdated = 'SCHEDULE_UPDATED',
    ScheduleCancelled = 'SCHEDULE_CANCELLED',
    AssignmentCreated = 'ASSIGNMENT_CREATED',
    AssignmentRemoved = 'ASSIGNMENT_REMOVED'
};



function isOptionalShopAuditFilterPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type ShopAuditFilterOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createShopAuditFilterPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createShopAuditFilterOptionalProperties(
    ...properties: ShopAuditFilterOptionalProperty[]
): ReadonlyArray<ShopAuditFilterOptionalProperty> {
    return properties;
}

export function instanceOfShopAuditFilter(value: object): value is ShopAuditFilter {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createShopAuditFilterPropertyNames();
    const optionalStringProperties = createShopAuditFilterOptionalProperties({ name: 'workorderId', nullable: false }, { name: 'appointmentId', nullable: false }, { name: 'mechanicId', nullable: false }, { name: 'actorUserId', nullable: false }, { name: 'eventType', nullable: false }, { name: 'locationId', nullable: false }, );
    const optionalNumberProperties = createShopAuditFilterOptionalProperties();
    const optionalBooleanProperties = createShopAuditFilterOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalShopAuditFilterPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalShopAuditFilterPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalShopAuditFilterPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

