/**
 * Positivity Order API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Result of applying a price override to an order line
 */
export interface PriceOverrideResult { 
    /**
     * Unique identifier of the created price override
     */
    overrideId: string;
    /**
     * Identifier of the order the override applies to
     */
    orderId: string;
    /**
     * Identifier of the order line the override applies to
     */
    orderLineId: string;
    /**
     * Identifier of the product on the overridden line
     */
    productId: string;
    /**
     * Original price before the override
     */
    originalPrice: number;
    /**
     * Overridden price applied to the line
     */
    overridePrice: number;
    /**
     * Absolute discount amount granted by the override
     */
    discountAmount: number;
    /**
     * Discount expressed as a percentage of the original price
     */
    discountPercentage: number;
    /**
     * Reason code supplied for the override
     */
    reasonCode: string;
    /**
     * Free-text justification supporting the override
     */
    justification?: string;
    /**
     * Override status; APPROVED means applied immediately, PENDING_APPROVAL means queued for review
     */
    status: string;
    /**
     * Whether the override required approval
     */
    requiresApproval: boolean;
    /**
     * Whether the override affects sales commission
     */
    affectsCommission: boolean;
    /**
     * Identifier of the user who requested the override
     */
    requestedByUserId: string;
    /**
     * Timestamp when the override was created
     */
    createdAt: string;
    /**
     * Optional human-readable message describing the result
     */
    message?: string;
}

function isOptionalPriceOverrideResultPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type PriceOverrideResultOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createPriceOverrideResultPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createPriceOverrideResultOptionalProperties(
    ...properties: PriceOverrideResultOptionalProperty[]
): ReadonlyArray<PriceOverrideResultOptionalProperty> {
    return properties;
}

export function instanceOfPriceOverrideResult(value: object): value is PriceOverrideResult {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createPriceOverrideResultPropertyNames('overrideId', 'orderId', 'orderLineId', 'productId', 'originalPrice', 'overridePrice', 'discountAmount', 'discountPercentage', 'reasonCode', 'status', 'requiresApproval', 'affectsCommission', 'requestedByUserId', 'createdAt', );
    const optionalStringProperties = createPriceOverrideResultOptionalProperties({ name: 'overrideId', nullable: false }, { name: 'orderId', nullable: false }, { name: 'orderLineId', nullable: false }, { name: 'productId', nullable: false }, { name: 'reasonCode', nullable: false }, { name: 'justification', nullable: false }, { name: 'status', nullable: false }, { name: 'requestedByUserId', nullable: false }, { name: 'message', nullable: false }, );
    const optionalNumberProperties = createPriceOverrideResultOptionalProperties({ name: 'originalPrice', nullable: false }, { name: 'overridePrice', nullable: false }, { name: 'discountAmount', nullable: false }, { name: 'discountPercentage', nullable: false }, );
    const optionalBooleanProperties = createPriceOverrideResultOptionalProperties({ name: 'requiresApproval', nullable: false }, { name: 'affectsCommission', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalPriceOverrideResultPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalPriceOverrideResultPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalPriceOverrideResultPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

