/**
 * Positivity Order API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One requested return line
 */
export interface ReturnLineRequest {
    /**
     * Disposition of the returned item
     */
    condition: ReturnLineRequestConditionEnum;
    /**
     * The sold line (order line id) being returned against
     */
    originalOrderLineId: string;
    /**
     * Units to return (capped at the un-refunded remainder)
     */
    returnQty: number;
    /**
     * Returned serials, when the sale captured them
     */
    serialNumbers?: Array<string>;
}
export enum ReturnLineRequestConditionEnum {
    Restock = 'RESTOCK',
    Scrap = 'SCRAP',
    Warranty = 'WARRANTY'
};



function isOptionalReturnLineRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type ReturnLineRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createReturnLineRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createReturnLineRequestOptionalProperties(
    ...properties: ReturnLineRequestOptionalProperty[]
): ReadonlyArray<ReturnLineRequestOptionalProperty> {
    return properties;
}

export function instanceOfReturnLineRequest(value: object): value is ReturnLineRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createReturnLineRequestPropertyNames('condition', 'originalOrderLineId', 'returnQty', );
    const optionalStringProperties = createReturnLineRequestOptionalProperties({ name: 'condition', nullable: false }, { name: 'originalOrderLineId', nullable: false }, );
    const optionalNumberProperties = createReturnLineRequestOptionalProperties({ name: 'returnQty', nullable: false }, );
    const optionalBooleanProperties = createReturnLineRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalReturnLineRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalReturnLineRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalReturnLineRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

