export * from './adminAccountStateAPI.service';
import { AdminAccountStateAPIService } from './adminAccountStateAPI.service';
export * from './audit.service';
import { AuditService } from './audit.service';
export * from './authAPI.service';
import { AuthAPIService } from './authAPI.service';
export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './jWTAPI.service';
import { JWTAPIService } from './jWTAPI.service';
export * from './permissionRegistry.service';
import { PermissionRegistryService } from './permissionRegistry.service';
export * from './principalRoleManagement.service';
import { PrincipalRoleManagementService } from './principalRoleManagement.service';
export * from './roleManagement.service';
import { RoleManagementService } from './roleManagement.service';
export * from './selfRegistrationReviewAPI.service';
import { SelfRegistrationReviewAPIService } from './selfRegistrationReviewAPI.service';
export * from './userAPI.service';
import { UserAPIService } from './userAPI.service';
export * from './userRoleManagement.service';
import { UserRoleManagementService } from './userRoleManagement.service';
export const APIS = [AdminAccountStateAPIService, AuditService, AuthAPIService, AuthorizationService, JWTAPIService, PermissionRegistryService, PrincipalRoleManagementService, RoleManagementService, SelfRegistrationReviewAPIService, UserAPIService, UserRoleManagementService];
