/**
 * Positivity Tenant API
 *
 * Contact: platform@durionpos.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload for an account contact
 */
export interface AccountContactRequest {
    /**
     * Email address
     */
    email: string;
    /**
     * Contact\'s name
     */
    name: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Role on the account
     */
    role: AccountContactRequestRoleEnum;
}
export enum AccountContactRequestRoleEnum {
    Owner = 'OWNER',
    Billing = 'BILLING',
    Technical = 'TECHNICAL'
};



function isOptionalAccountContactRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type AccountContactRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createAccountContactRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createAccountContactRequestOptionalProperties(
    ...properties: AccountContactRequestOptionalProperty[]
): ReadonlyArray<AccountContactRequestOptionalProperty> {
    return properties;
}

export function instanceOfAccountContactRequest(value: object): value is AccountContactRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createAccountContactRequestPropertyNames('email', 'name', 'role', );
    const optionalStringProperties = createAccountContactRequestOptionalProperties({ name: 'email', nullable: false }, { name: 'name', nullable: false }, { name: 'phone', nullable: false }, { name: 'role', nullable: false }, );
    const optionalNumberProperties = createAccountContactRequestOptionalProperties();
    const optionalBooleanProperties = createAccountContactRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalAccountContactRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalAccountContactRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalAccountContactRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

