export * from './bayAPI.service';
import { BayAPIService } from './bayAPI.service';
export * from './locationAPI.service';
import { LocationAPIService } from './locationAPI.service';
export * from './locationBulkIngestAPI.service';
import { LocationBulkIngestAPIService } from './locationBulkIngestAPI.service';
export * from './mobileUnitAPI.service';
import { MobileUnitAPIService } from './mobileUnitAPI.service';
export * from './mobileUnitEligibilityController.service';
import { MobileUnitEligibilityControllerService } from './mobileUnitEligibilityController.service';
export * from './serviceAreaAPI.service';
import { ServiceAreaAPIService } from './serviceAreaAPI.service';
export * from './siteDefaultsAPI.service';
import { SiteDefaultsAPIService } from './siteDefaultsAPI.service';
export * from './storageLocationAPI.service';
import { StorageLocationAPIService } from './storageLocationAPI.service';
export * from './storageLocationValidationController.service';
import { StorageLocationValidationControllerService } from './storageLocationValidationController.service';
export * from './travelBufferPolicyAPI.service';
import { TravelBufferPolicyAPIService } from './travelBufferPolicyAPI.service';
export const APIS = [BayAPIService, LocationAPIService, LocationBulkIngestAPIService, MobileUnitAPIService, MobileUnitEligibilityControllerService, ServiceAreaAPIService, SiteDefaultsAPIService, StorageLocationAPIService, StorageLocationValidationControllerService, TravelBufferPolicyAPIService];
