/**
 * Positivity Location API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { BulkIngestRequestBayBulkIngestRecord } from '../src/models/bulkIngestRequestBayBulkIngestRecord';
// @ts-ignore
import { BulkIngestResponse } from '../src/models/bulkIngestResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class BayBulkIngestAPIService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Create Service Bays in Bulk
     * Creates many service bays at once, one per record. Use this tool when commissioning a location or seeding an environment; use createBay instead for a single bay. Preconditions: each row\&#39;s location must exist, and bayType must name a known bay type. Required inputs: jobId (UUID), locationId (UUID) and records, each with a name, a bayType and maxConcurrentVehicles; a record\&#39;s own locationId overrides the batch one. Emits a LOCATION_BAY_BULK_INGEST event and a bay-created event per row. Re-running the same file is safe: a bay name already present at its location is reported as already existing rather than as a failure. Returns 200 with a per-record result; check each result rather than the status alone. 
     * @endpoint post /v1/locations/bays/bulk-ingest
     * @param bulkIngestRequestBayBulkIngestRecord Service bays to create.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public bulkIngestBays(bulkIngestRequestBayBulkIngestRecord: BulkIngestRequestBayBulkIngestRecord, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<BulkIngestResponse>;
    public bulkIngestBays(bulkIngestRequestBayBulkIngestRecord: BulkIngestRequestBayBulkIngestRecord, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<BulkIngestResponse>>;
    public bulkIngestBays(bulkIngestRequestBayBulkIngestRecord: BulkIngestRequestBayBulkIngestRecord, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<BulkIngestResponse>>;
    public bulkIngestBays(bulkIngestRequestBayBulkIngestRecord: BulkIngestRequestBayBulkIngestRecord, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (bulkIngestRequestBayBulkIngestRecord === null || bulkIngestRequestBayBulkIngestRecord === undefined) {
            throw new Error('Required parameter bulkIngestRequestBayBulkIngestRecord was null or undefined when calling bulkIngestBays.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/locations/bays/bulk-ingest`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<BulkIngestResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: bulkIngestRequestBayBulkIngestRecord,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
