/**
 * Positivity Location API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoverageRuleRequest } from './coverageRuleRequest';


/**
 * Mobile unit creation request body
 */
export interface MobileUnitRequest { 
    name?: string;
    baseLocationId?: string;
    status?: string;
    travelBufferPolicyId?: string;
    notes?: string;
    capabilityIds?: Array<string>;
    coverageRules?: Array<CoverageRuleRequest>;
}

