/**
 * Positivity Location API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StorageLocationPatchRequest { 
    name?: string;
    barcode?: string;
    status?: StorageLocationPatchRequestStatusEnum;
    parentStorageLocationId?: string;
    destinationStorageLocationId?: string;
    capacity?: { [key: string]: any; };
    temperature?: { [key: string]: any; };
}
export enum StorageLocationPatchRequestStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Maintenance = 'MAINTENANCE',
    Quarantined = 'QUARANTINED'
};



