export * from './employeeAPI.service';
import { EmployeeAPIService } from './employeeAPI.service';
export * from './peopleAPI.service';
import { PeopleAPIService } from './peopleAPI.service';
export * from './peopleAccessControl.service';
import { PeopleAccessControlService } from './peopleAccessControl.service';
export * from './peopleAvailabilityAPI.service';
import { PeopleAvailabilityAPIService } from './peopleAvailabilityAPI.service';
export * from './peopleBulkIngestAPI.service';
import { PeopleBulkIngestAPIService } from './peopleBulkIngestAPI.service';
export * from './peopleExceptions.service';
import { PeopleExceptionsService } from './peopleExceptions.service';
export * from './peopleReportsAPI.service';
import { PeopleReportsAPIService } from './peopleReportsAPI.service';
export * from './peopleStaffingAssignments.service';
import { PeopleStaffingAssignmentsService } from './peopleStaffingAssignments.service';
export * from './peopleTimeEntries.service';
import { PeopleTimeEntriesService } from './peopleTimeEntries.service';
export * from './timeEntryApprovalAPI.service';
import { TimeEntryApprovalAPIService } from './timeEntryApprovalAPI.service';
export * from './timekeepingApprovalAPI.service';
import { TimekeepingApprovalAPIService } from './timekeepingApprovalAPI.service';
export * from './userPersonLinkingAPI.service';
import { UserPersonLinkingAPIService } from './userPersonLinkingAPI.service';
export * from './workSessionsAPI.service';
import { WorkSessionsAPIService } from './workSessionsAPI.service';
export const APIS = [EmployeeAPIService, PeopleAPIService, PeopleAccessControlService, PeopleAvailabilityAPIService, PeopleBulkIngestAPIService, PeopleExceptionsService, PeopleReportsAPIService, PeopleStaffingAssignmentsService, PeopleTimeEntriesService, TimeEntryApprovalAPIService, TimekeepingApprovalAPIService, UserPersonLinkingAPIService, WorkSessionsAPIService];
