/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkIngestResult } from './bulkIngestResult';


export interface BulkIngestResponse { 
    totalSubmitted?: number;
    successCount?: number;
    failureCount?: number;
    results?: Array<BulkIngestResult>;
}

