/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Contact point details
 */
export interface ContactPointDto { 
    /**
     * Contact point ID
     */
    contactPointId?: string;
    /**
     * Type of contact point
     */
    contactType?: ContactPointDtoContactTypeEnum;
    /**
     * Contact value
     */
    value?: string;
    primary?: boolean;
}
export enum ContactPointDtoContactTypeEnum {
    Email = 'EMAIL',
    PhoneMobile = 'PHONE_MOBILE',
    PhoneHome = 'PHONE_HOME',
    PhoneWork = 'PHONE_WORK',
    Fax = 'FAX'
};



