/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactPreferences { 
    emailOptIn?: boolean;
    smsOptIn?: boolean;
    phoneOptIn?: boolean;
    doNotContact?: boolean;
    preferredContactMethod?: string;
    preferredLanguage?: string;
}

