/**
 * Positivity Customer API
 * API documentation for the Customer service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to create a relationship between a commercial account and an individual
 */
export interface CreatePartyRelationshipRequest { 
    /**
     * ID of the individual person
     */
    personId: string;
    /**
     * Roles for this relationship
     */
    roles: Set<CreatePartyRelationshipRequestRolesEnum>;
    /**
     * Date when this relationship becomes effective
     */
    effectiveStartDate: string;
    /**
     * Date when this relationship ends (null means no end date)
     */
    effectiveEndDate?: string;
    primaryBillingContact?: boolean;
}
export enum CreatePartyRelationshipRequestRolesEnum {
    Approver = 'APPROVER',
    Billing = 'BILLING',
    PrimaryContact = 'PRIMARY_CONTACT',
    Driver = 'DRIVER',
    Technical = 'TECHNICAL'
};



