/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One recorded touch on a party\'s interaction timeline
 */
export interface CustomerInteractionResponse { 
    /**
     * Interaction identifier
     */
    interactionId: string;
    /**
     * Party the touch belongs to
     */
    partyId: string;
    /**
     * Contact reached, when the touch targeted one
     */
    contactId?: string;
    /**
     * Kind of touch
     */
    type: CustomerInteractionResponseTypeEnum;
    /**
     * Channel used
     */
    channel?: CustomerInteractionResponseChannelEnum;
    /**
     * Who initiated the touch
     */
    direction: CustomerInteractionResponseDirectionEnum;
    /**
     * Campaign the touch belongs to
     */
    campaignId?: string;
    /**
     * Campaign code
     */
    campaignCode?: string;
    /**
     * Short subject line
     */
    subject?: string;
    /**
     * Human summary of the touch
     */
    summary?: string;
    /**
     * Body text, redacted before it leaves the service
     */
    body?: string;
    /**
     * Actor that recorded the touch
     */
    actor?: string;
    /**
     * Workorder the touch originated from
     */
    sourceWorkorderId?: string;
    /**
     * When the touch occurred
     */
    occurredAt: string;
}
export enum CustomerInteractionResponseTypeEnum {
    CampaignSend = 'CAMPAIGN_SEND',
    Email = 'EMAIL',
    Sms = 'SMS',
    Call = 'CALL',
    FollowUp = 'FOLLOW_UP',
    Note = 'NOTE',
    WorkorderNote = 'WORKORDER_NOTE'
};
export enum CustomerInteractionResponseChannelEnum {
    Email = 'EMAIL',
    Sms = 'SMS'
};
export enum CustomerInteractionResponseDirectionEnum {
    Outbound = 'OUTBOUND',
    Inbound = 'INBOUND'
};



function isOptionalCustomerInteractionResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CustomerInteractionResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCustomerInteractionResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCustomerInteractionResponseOptionalProperties(
    ...properties: CustomerInteractionResponseOptionalProperty[]
): ReadonlyArray<CustomerInteractionResponseOptionalProperty> {
    return properties;
}

export function instanceOfCustomerInteractionResponse(value: object): value is CustomerInteractionResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCustomerInteractionResponsePropertyNames('interactionId', 'partyId', 'type', 'direction', 'occurredAt', );
    const optionalStringProperties = createCustomerInteractionResponseOptionalProperties({ name: 'interactionId', nullable: false }, { name: 'partyId', nullable: false }, { name: 'contactId', nullable: false }, { name: 'type', nullable: false }, { name: 'channel', nullable: false }, { name: 'direction', nullable: false }, { name: 'campaignId', nullable: false }, { name: 'campaignCode', nullable: false }, { name: 'subject', nullable: false }, { name: 'summary', nullable: false }, { name: 'body', nullable: false }, { name: 'actor', nullable: false }, { name: 'sourceWorkorderId', nullable: false }, );
    const optionalNumberProperties = createCustomerInteractionResponseOptionalProperties();
    const optionalBooleanProperties = createCustomerInteractionResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCustomerInteractionResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCustomerInteractionResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCustomerInteractionResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

