/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetCommunicationPreferencesResponse { 
    partyId?: string;
    version?: string;
    emailPreference?: string;
    smsPreference?: string;
    phonePreference?: string;
    marketingPreference?: string;
    consentFlags?: { [key: string]: boolean; };
    preferencesNote?: string;
    updatedAt?: string;
    updateSource?: string;
}

function isOptionalGetCommunicationPreferencesResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type GetCommunicationPreferencesResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createGetCommunicationPreferencesResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createGetCommunicationPreferencesResponseOptionalProperties(
    ...properties: GetCommunicationPreferencesResponseOptionalProperty[]
): ReadonlyArray<GetCommunicationPreferencesResponseOptionalProperty> {
    return properties;
}

export function instanceOfGetCommunicationPreferencesResponse(value: object): value is GetCommunicationPreferencesResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createGetCommunicationPreferencesResponsePropertyNames();
    const optionalStringProperties = createGetCommunicationPreferencesResponseOptionalProperties({ name: 'partyId', nullable: false }, { name: 'version', nullable: false }, { name: 'emailPreference', nullable: false }, { name: 'smsPreference', nullable: false }, { name: 'phonePreference', nullable: false }, { name: 'marketingPreference', nullable: false }, { name: 'preferencesNote', nullable: false }, { name: 'updatedAt', nullable: false }, { name: 'updateSource', nullable: false }, );
    const optionalNumberProperties = createGetCommunicationPreferencesResponseOptionalProperties();
    const optionalBooleanProperties = createGetCommunicationPreferencesResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalGetCommunicationPreferencesResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalGetCommunicationPreferencesResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalGetCommunicationPreferencesResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

