/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SegmentResponsePredicate } from './segmentResponsePredicate';


/**
 * A saved audience segment
 */
export interface SegmentResponse { 
    /**
     * Segment identifier
     */
    segmentId: string;
    /**
     * Segment name
     */
    name: string;
    /**
     * What the segment is for
     */
    description?: string;
    /**
     * Targeted party kind
     */
    audienceType: SegmentResponseAudienceTypeEnum;
    /**
     * How membership is determined
     */
    type: SegmentResponseTypeEnum;
    predicate?: SegmentResponsePredicate;
    /**
     * Whether the segment can be bound to a campaign
     */
    active: boolean;
    /**
     * Pinned member count for STATIC segments; null for DYNAMIC
     */
    memberCount?: number;
    /**
     * Creation timestamp
     */
    createdAt?: string;
    /**
     * Last update timestamp
     */
    updatedAt?: string;
}
export enum SegmentResponseAudienceTypeEnum {
    Commercial = 'COMMERCIAL',
    Individual = 'INDIVIDUAL'
};
export enum SegmentResponseTypeEnum {
    Static = 'STATIC',
    Dynamic = 'DYNAMIC'
};



function isOptionalSegmentResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type SegmentResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createSegmentResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createSegmentResponseOptionalProperties(
    ...properties: SegmentResponseOptionalProperty[]
): ReadonlyArray<SegmentResponseOptionalProperty> {
    return properties;
}

export function instanceOfSegmentResponse(value: object): value is SegmentResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createSegmentResponsePropertyNames('segmentId', 'name', 'audienceType', 'type', 'active', );
    const optionalStringProperties = createSegmentResponseOptionalProperties({ name: 'segmentId', nullable: false }, { name: 'name', nullable: false }, { name: 'description', nullable: false }, { name: 'audienceType', nullable: false }, { name: 'type', nullable: false }, );
    const optionalNumberProperties = createSegmentResponseOptionalProperties({ name: 'memberCount', nullable: false }, );
    const optionalBooleanProperties = createSegmentResponseOptionalProperties({ name: 'active', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalSegmentResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalSegmentResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalSegmentResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

