/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Communication preferences to set
 */
export interface UpsertCommunicationPreferencesRequest { 
    /**
     * Optimistic locking version; required for updates, omitted for creates
     */
    version?: string;
    /**
     * Email preference (OPT_IN|OPT_OUT|NOT_APPLICABLE)
     */
    emailPreference?: string;
    /**
     * SMS preference (OPT_IN|OPT_OUT|NOT_APPLICABLE)
     */
    smsPreference?: string;
    /**
     * Phone preference (OPT_IN|OPT_OUT|NOT_APPLICABLE)
     */
    phonePreference?: string;
    /**
     * Marketing communications preference (OPT_IN|OPT_OUT)
     */
    marketingPreference?: string;
    /**
     * Consent flags keyed by consent type; field names depend on legal requirements
     */
    consentFlags?: { [key: string]: boolean; };
    /**
     * User-provided note or preferences summary
     */
    preferencesNote?: string;
    /**
     * Source of update (APP|API|ADMIN)
     */
    updateSource?: string;
}

function isOptionalUpsertCommunicationPreferencesRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type UpsertCommunicationPreferencesRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createUpsertCommunicationPreferencesRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createUpsertCommunicationPreferencesRequestOptionalProperties(
    ...properties: UpsertCommunicationPreferencesRequestOptionalProperty[]
): ReadonlyArray<UpsertCommunicationPreferencesRequestOptionalProperty> {
    return properties;
}

export function instanceOfUpsertCommunicationPreferencesRequest(value: object): value is UpsertCommunicationPreferencesRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createUpsertCommunicationPreferencesRequestPropertyNames();
    const optionalStringProperties = createUpsertCommunicationPreferencesRequestOptionalProperties({ name: 'version', nullable: false }, { name: 'emailPreference', nullable: false }, { name: 'smsPreference', nullable: false }, { name: 'phonePreference', nullable: false }, { name: 'marketingPreference', nullable: false }, { name: 'preferencesNote', nullable: false }, { name: 'updateSource', nullable: false }, );
    const optionalNumberProperties = createUpsertCommunicationPreferencesRequestOptionalProperties();
    const optionalBooleanProperties = createUpsertCommunicationPreferencesRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalUpsertCommunicationPreferencesRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalUpsertCommunicationPreferencesRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalUpsertCommunicationPreferencesRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

