/**
 * Positivity Customer API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VehicleSummary { 
    vehicleId?: string;
    vin?: string;
    licensePlate?: string;
    make?: string;
    model?: string;
    year?: number;
}

function isOptionalVehicleSummaryPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type VehicleSummaryOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createVehicleSummaryPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createVehicleSummaryOptionalProperties(
    ...properties: VehicleSummaryOptionalProperty[]
): ReadonlyArray<VehicleSummaryOptionalProperty> {
    return properties;
}

export function instanceOfVehicleSummary(value: object): value is VehicleSummary {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createVehicleSummaryPropertyNames();
    const optionalStringProperties = createVehicleSummaryOptionalProperties({ name: 'vehicleId', nullable: false }, { name: 'vin', nullable: false }, { name: 'licensePlate', nullable: false }, { name: 'make', nullable: false }, { name: 'model', nullable: false }, );
    const optionalNumberProperties = createVehicleSummaryOptionalProperties({ name: 'year', nullable: false }, );
    const optionalBooleanProperties = createVehicleSummaryOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalVehicleSummaryPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalVehicleSummaryPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalVehicleSummaryPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

