/**
 * Positivity Price API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { BulkIngestRequestLaborRateAdjustmentBulkIngestRecord } from '../src/models/bulkIngestRequestLaborRateAdjustmentBulkIngestRecord';
// @ts-ignore
import { BulkIngestResponse } from '../src/models/bulkIngestResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class LaborRateAdjustmentBulkIngestAPIService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Bulk Import Labor Matrix Adjustments
     * Imports a batch of labor-matrix adjustment steps in one call, storing each whose scope, code and start instant are not already taken, with a per-row verdict. Use this tool to load a whole matrix at once, where the steps\&#39; sequences relative to each other are the point; do not use createLaborRateAdjustment, which stores one step at a time and cannot show that ordering. Preconditions: a row whose location, category, adjustmentCode and effectiveFrom are already held is answered with the stored step unchanged, because a step that has priced an invoice is never rewritten. Required inputs: jobId (UUID), locationId (UUID) and a non-empty records array; per record, adjustmentCode, adjustmentType, adjustmentValue, sequence and effectiveFrom, with the step\&#39;s own locationId, operationCategory, description and effectiveTo optional. Emits a PRICE_LABOR_RATE_ADJUSTMENT_BULK_INGEST event; percentage steps compound in sequence order, so a batch that renumbers them changes what the matrix charges. Returns 200 even when rows fail, so callers must inspect successCount, failureCount and the per-row results rather than the HTTP status. A row pricing refused carries errorCode LABOR_RATE_ADJUSTMENT_INGEST_FAILED and the reason; a row lost to a server-side fault carries INTERNAL_ERROR and a correlationId to quote.
     * @endpoint post /v1/labor-rate-adjustments/bulk-ingest
     * @param bulkIngestRequestLaborRateAdjustmentBulkIngestRecord Batch of labor-matrix adjustment steps to store for one ingest job.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public bulkIngestLaborRateAdjustments(bulkIngestRequestLaborRateAdjustmentBulkIngestRecord: BulkIngestRequestLaborRateAdjustmentBulkIngestRecord, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<BulkIngestResponse>;
    public bulkIngestLaborRateAdjustments(bulkIngestRequestLaborRateAdjustmentBulkIngestRecord: BulkIngestRequestLaborRateAdjustmentBulkIngestRecord, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<BulkIngestResponse>>;
    public bulkIngestLaborRateAdjustments(bulkIngestRequestLaborRateAdjustmentBulkIngestRecord: BulkIngestRequestLaborRateAdjustmentBulkIngestRecord, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<BulkIngestResponse>>;
    public bulkIngestLaborRateAdjustments(bulkIngestRequestLaborRateAdjustmentBulkIngestRecord: BulkIngestRequestLaborRateAdjustmentBulkIngestRecord, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (bulkIngestRequestLaborRateAdjustmentBulkIngestRecord === null || bulkIngestRequestLaborRateAdjustmentBulkIngestRecord === undefined) {
            throw new Error('Required parameter bulkIngestRequestLaborRateAdjustmentBulkIngestRecord was null or undefined when calling bulkIngestLaborRateAdjustments.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/labor-rate-adjustments/bulk-ingest`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<BulkIngestResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: bulkIngestRequestLaborRateAdjustmentBulkIngestRecord,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
