/**
 * Positivity Product API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lightweight product summary for search results
 */
export interface ProductSummary { 
    /**
     * Unique product identifier
     */
    productId?: string;
    /**
     * Product name
     */
    name?: string;
    /**
     * Stock Keeping Unit
     */
    sku?: string;
    /**
     * Category name
     */
    category?: string;
    /**
     * URL of the primary product thumbnail image
     */
    thumbnailUrl?: string;
    /**
     * Manufacturer brand name
     */
    manufacturerBrand?: string;
}

function isOptionalProductSummaryPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type ProductSummaryOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createProductSummaryPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createProductSummaryOptionalProperties(
    ...properties: ProductSummaryOptionalProperty[]
): ReadonlyArray<ProductSummaryOptionalProperty> {
    return properties;
}

export function instanceOfProductSummary(value: object): value is ProductSummary {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createProductSummaryPropertyNames();
    const optionalStringProperties = createProductSummaryOptionalProperties({ name: 'productId', nullable: false }, { name: 'name', nullable: false }, { name: 'sku', nullable: false }, { name: 'category', nullable: false }, { name: 'thumbnailUrl', nullable: false }, { name: 'manufacturerBrand', nullable: false }, );
    const optionalNumberProperties = createProductSummaryOptionalProperties();
    const optionalBooleanProperties = createProductSummaryOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalProductSummaryPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalProductSummaryPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalProductSummaryPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

