/**
 * Positivity Product API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A reviewer\'s decision about a tread design awaiting review.
 */
export interface TreadDesignResolveRequest {
    /**
     * ATTACH, REJECT or DEFER.
     */
    action: TreadDesignResolveRequestActionEnum;
    /**
     * When a deferred design should come back. DEFER only.
     */
    deferUntil?: string;
    /**
     * Why. Stored with the design and shown in the worklist.
     */
    note?: string;
    /**
     * Products to attach. Required for ATTACH, rejected for the other actions.
     */
    productIds?: Array<string>;
}
export enum TreadDesignResolveRequestActionEnum {
    Attach = 'ATTACH',
    Reject = 'REJECT',
    Defer = 'DEFER'
};



function isOptionalTreadDesignResolveRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type TreadDesignResolveRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createTreadDesignResolveRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createTreadDesignResolveRequestOptionalProperties(
    ...properties: TreadDesignResolveRequestOptionalProperty[]
): ReadonlyArray<TreadDesignResolveRequestOptionalProperty> {
    return properties;
}

export function instanceOfTreadDesignResolveRequest(value: object): value is TreadDesignResolveRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createTreadDesignResolveRequestPropertyNames('action', );
    const optionalStringProperties = createTreadDesignResolveRequestOptionalProperties({ name: 'action', nullable: false }, { name: 'deferUntil', nullable: false }, { name: 'note', nullable: false }, );
    const optionalNumberProperties = createTreadDesignResolveRequestOptionalProperties();
    const optionalBooleanProperties = createTreadDesignResolveRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalTreadDesignResolveRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalTreadDesignResolveRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalTreadDesignResolveRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

