/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AsnLineResponse { 
    asnLineId?: string;
    poId?: string;
    sku?: string;
    quantityShipped?: number;
    quantityReceived?: number;
    unitOfMeasure?: string;
    lotNumber?: string;
}

