/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AsnLineResponse { 
    asnLineId?: string;
    poId?: string;
    sku?: string;
    quantityShipped?: number;
    quantityReceived?: number;
    unitOfMeasure?: string;
    lotNumber?: string;
}

function isOptionalAsnLineResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type AsnLineResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createAsnLineResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createAsnLineResponseOptionalProperties(
    ...properties: AsnLineResponseOptionalProperty[]
): ReadonlyArray<AsnLineResponseOptionalProperty> {
    return properties;
}

export function instanceOfAsnLineResponse(value: object): value is AsnLineResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createAsnLineResponsePropertyNames();
    const optionalStringProperties = createAsnLineResponseOptionalProperties({ name: 'asnLineId', nullable: false }, { name: 'poId', nullable: false }, { name: 'sku', nullable: false }, { name: 'unitOfMeasure', nullable: false }, { name: 'lotNumber', nullable: false }, );
    const optionalNumberProperties = createAsnLineResponseOptionalProperties({ name: 'quantityShipped', nullable: false }, { name: 'quantityReceived', nullable: false }, );
    const optionalBooleanProperties = createAsnLineResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalAsnLineResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalAsnLineResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalAsnLineResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

