/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateGoodsReceiptLineRequest } from './createGoodsReceiptLineRequest';


/**
 * Request payload to record a goods receipt for inventory received against a purchase order, optionally linked to an ASN
 */
export interface CreateGoodsReceiptRequest {
    /**
     * Identifier of the advance shipping notice (ASN) this receipt fulfills, if applicable
     */
    asnId?: string;
    /**
     * Received line items detailing the SKUs and quantities in this goods receipt
     */
    lines: Array<CreateGoodsReceiptLineRequest>;
    /**
     * Identifier of the location where the goods are received into inventory
     */
    locationId: string;
    /**
     * Identifier of the purchase order the goods are received against
     */
    poId: string;
}

function isOptionalCreateGoodsReceiptRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CreateGoodsReceiptRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCreateGoodsReceiptRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCreateGoodsReceiptRequestOptionalProperties(
    ...properties: CreateGoodsReceiptRequestOptionalProperty[]
): ReadonlyArray<CreateGoodsReceiptRequestOptionalProperty> {
    return properties;
}

export function instanceOfCreateGoodsReceiptRequest(value: object): value is CreateGoodsReceiptRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCreateGoodsReceiptRequestPropertyNames('lines', 'locationId', 'poId', );
    const optionalStringProperties = createCreateGoodsReceiptRequestOptionalProperties({ name: 'asnId', nullable: false }, { name: 'locationId', nullable: false }, { name: 'poId', nullable: false }, );
    const optionalNumberProperties = createCreateGoodsReceiptRequestOptionalProperties();
    const optionalBooleanProperties = createCreateGoodsReceiptRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCreateGoodsReceiptRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCreateGoodsReceiptRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCreateGoodsReceiptRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

