/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to create a replenishment policy defining min/max stock thresholds for an item at a location
 */
export interface CreateReplenishmentPolicyRequest { 
    /**
     * Whether the policy participates in replenishment evaluation; defaults to true
     */
    active?: boolean;
    /**
     * SKU of the item the replenishment policy applies to
     */
    itemSKU: string;
    /**
     * Per-policy lead-time override in days; takes precedence over vendor-feed lead-time estimates and the configured default
     */
    leadTimeDaysOverride?: number;
    /**
     * Identifier of the location the replenishment policy applies to
     */
    locationId: string;
    /**
     * Maximum on-hand quantity replenishment aims to restock up to
     */
    maximumQuantity: number;
    minimumLessThanMaximum?: boolean;
    /**
     * Minimum on-hand quantity that triggers replenishment when reached
     */
    minimumQuantity: number;
    /**
     * Round the computed replenishment quantity up to the nearest multiple of this value. When omitted, defaults to the vendor-feed pack size for the SKU when one is known (greater than 1); otherwise no rounding is applied.
     */
    orderMultiple?: number;
    /**
     * Preferred sourcing channel for replenishing this policy\'s pick face; defaults to EITHER
     */
    preferredSourceType?: CreateReplenishmentPolicyRequestPreferredSourceTypeEnum;
}
export enum CreateReplenishmentPolicyRequestPreferredSourceTypeEnum {
    InternalTransfer = 'INTERNAL_TRANSFER',
    Purchase = 'PURCHASE',
    Either = 'EITHER'
};



function isOptionalCreateReplenishmentPolicyRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CreateReplenishmentPolicyRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCreateReplenishmentPolicyRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCreateReplenishmentPolicyRequestOptionalProperties(
    ...properties: CreateReplenishmentPolicyRequestOptionalProperty[]
): ReadonlyArray<CreateReplenishmentPolicyRequestOptionalProperty> {
    return properties;
}

export function instanceOfCreateReplenishmentPolicyRequest(value: object): value is CreateReplenishmentPolicyRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCreateReplenishmentPolicyRequestPropertyNames('itemSKU', 'locationId', 'maximumQuantity', 'minimumQuantity', );
    const optionalStringProperties = createCreateReplenishmentPolicyRequestOptionalProperties({ name: 'itemSKU', nullable: false }, { name: 'locationId', nullable: false }, { name: 'preferredSourceType', nullable: false }, );
    const optionalNumberProperties = createCreateReplenishmentPolicyRequestOptionalProperties({ name: 'leadTimeDaysOverride', nullable: false }, { name: 'maximumQuantity', nullable: false }, { name: 'minimumQuantity', nullable: false }, { name: 'orderMultiple', nullable: false }, );
    const optionalBooleanProperties = createCreateReplenishmentPolicyRequestOptionalProperties({ name: 'active', nullable: false }, { name: 'minimumLessThanMaximum', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCreateReplenishmentPolicyRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCreateReplenishmentPolicyRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCreateReplenishmentPolicyRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

