/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transfer } from './transfer';


export interface DeactivateLocationResponse { 
    sourceLocationId?: string;
    destinationLocationId?: string;
    status?: string;
    transfer?: Transfer;
}

export function instanceOfDeactivateLocationResponse(value: object): value is DeactivateLocationResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
    const _v = value as Record<string, unknown>;
    if ('sourceLocationId' in _v && typeof _v['sourceLocationId'] !== 'string') return false;
    if ('destinationLocationId' in _v && typeof _v['destinationLocationId'] !== 'string') return false;
    if ('status' in _v && typeof _v['status'] !== 'string') return false;
    return true;
}

