/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutawayLineItemRequest } from './putawayLineItemRequest';


export interface GeneratePutawayTasksRequest { 
    sourceReceiptId: string;
    productId?: string;
    quantity?: number;
    lineItems?: Array<PutawayLineItemRequest>;
}

