/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Inventory summary for a storage location
 */
export interface LocationInventoryInquiryResponse { 
    /**
     * Storage location identifier
     */
    locationId: string;
    /**
     * Current on-hand quantity across all stock items at the location
     */
    onHandQuantity: number;
}

