/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lot status change: QUARANTINE/RECALL a lot or release it back to ACTIVE
 */
export interface LotStatusUpdateRequest { 
    /**
     * Reason for the status change (mandatory; recorded for traceability)
     */
    reason: string;
    /**
     * Target lifecycle status. One of ACTIVE (release), QUARANTINED, RECALLED. CONSUMED is rejected (reconciler-owned).
     */
    status: LotStatusUpdateRequestStatusEnum;
}
export enum LotStatusUpdateRequestStatusEnum {
    Active = 'ACTIVE',
    Quarantined = 'QUARANTINED',
    Recalled = 'RECALLED',
    Consumed = 'CONSUMED'
};



function isOptionalLotStatusUpdateRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type LotStatusUpdateRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createLotStatusUpdateRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createLotStatusUpdateRequestOptionalProperties(
    ...properties: LotStatusUpdateRequestOptionalProperty[]
): ReadonlyArray<LotStatusUpdateRequestOptionalProperty> {
    return properties;
}

export function instanceOfLotStatusUpdateRequest(value: object): value is LotStatusUpdateRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createLotStatusUpdateRequestPropertyNames('reason', 'status', );
    const optionalStringProperties = createLotStatusUpdateRequestOptionalProperties({ name: 'reason', nullable: false }, { name: 'status', nullable: false }, );
    const optionalNumberProperties = createLotStatusUpdateRequestOptionalProperties();
    const optionalBooleanProperties = createLotStatusUpdateRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalLotStatusUpdateRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalLotStatusUpdateRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalLotStatusUpdateRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

