/**
 * Positivity Inventory API
 * API documentation for the Inventory service, accessible via the API Gateway.
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { PurchaseOrderResponse } from './purchaseOrderResponse';
import { SortObject } from './sortObject';


export interface PagePurchaseOrderResponse { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<PurchaseOrderResponse>;
    number?: number;
    first?: boolean;
    last?: boolean;
    pageable?: PageableObject;
    sort?: SortObject;
    numberOfElements?: number;
    empty?: boolean;
}

