/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pick task details describing a single SKU-and-location pick within a pick list
 */
export interface PickTaskResponse { 
    /**
     * Unique identifier of the pick task
     */
    pickTaskId: string;
    /**
     * Identifier of the pick list this task belongs to
     */
    pickListId: string;
    /**
     * Identifier of the SKU to be picked
     */
    skuId: string;
    /**
     * Identifier of the location the SKU is picked from
     */
    locationId: string;
    /**
     * Quantity required to satisfy this pick task
     */
    quantityRequired: number;
    /**
     * Quantity already picked against this task
     */
    quantityPicked: number;
    /**
     * Current status of the pick task
     */
    status: PickTaskResponseStatusEnum;
    /**
     * Ordinal position of this task in the pick sequence
     */
    sortOrder: number;
}
export enum PickTaskResponseStatusEnum {
    Pending = 'PENDING',
    NeedsReview = 'NEEDS_REVIEW',
    Picked = 'PICKED',
    Cancelled = 'CANCELLED'
};



function isOptionalPickTaskResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type PickTaskResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createPickTaskResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createPickTaskResponseOptionalProperties(
    ...properties: PickTaskResponseOptionalProperty[]
): ReadonlyArray<PickTaskResponseOptionalProperty> {
    return properties;
}

export function instanceOfPickTaskResponse(value: object): value is PickTaskResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createPickTaskResponsePropertyNames('pickTaskId', 'pickListId', 'skuId', 'locationId', 'quantityRequired', 'quantityPicked', 'status', 'sortOrder', );
    const optionalStringProperties = createPickTaskResponseOptionalProperties({ name: 'pickTaskId', nullable: false }, { name: 'pickListId', nullable: false }, { name: 'skuId', nullable: false }, { name: 'locationId', nullable: false }, { name: 'status', nullable: false }, );
    const optionalNumberProperties = createPickTaskResponseOptionalProperties({ name: 'quantityRequired', nullable: false }, { name: 'quantityPicked', nullable: false }, { name: 'sortOrder', nullable: false }, );
    const optionalBooleanProperties = createPickTaskResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalPickTaskResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalPickTaskResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalPickTaskResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

