/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceivePurchaseOrderLineRequest } from './receivePurchaseOrderLineRequest';


export interface ReceivePurchaseOrderRequest { 
    lines: Array<ReceivePurchaseOrderLineRequest>;
}

export function instanceOfReceivePurchaseOrderRequest(value: object): value is ReceivePurchaseOrderRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
    const _v = value as Record<string, unknown>;
    if (!('lines' in _v) || _v['lines'] === undefined) return false;
    return true;
}

