/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to reject a pending scrap document; no inventory changes are made
 */
export interface RejectScrapRequest { 
    /**
     * Reason explaining why the scrap is being rejected
     */
    rejectionReason: string;
}

function isOptionalRejectScrapRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type RejectScrapRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createRejectScrapRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createRejectScrapRequestOptionalProperties(
    ...properties: RejectScrapRequestOptionalProperty[]
): ReadonlyArray<RejectScrapRequestOptionalProperty> {
    return properties;
}

export function instanceOfRejectScrapRequest(value: object): value is RejectScrapRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createRejectScrapRequestPropertyNames('rejectionReason', );
    const optionalStringProperties = createRejectScrapRequestOptionalProperties({ name: 'rejectionReason', nullable: false }, );
    const optionalNumberProperties = createRejectScrapRequestOptionalProperties();
    const optionalBooleanProperties = createRejectScrapRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalRejectScrapRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalRejectScrapRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalRejectScrapRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

