/**
 * Positivity Inventory API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Requested SKU line of a transfer order
 */
export interface TransferOrderLineRequest {
    /**
     * Quantity requested for transfer; must be positive
     */
    requestedQty: number;
    /**
     * SKU / stock item identifier to transfer
     */
    sku: string;
}

function isOptionalTransferOrderLineRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type TransferOrderLineRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createTransferOrderLineRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createTransferOrderLineRequestOptionalProperties(
    ...properties: TransferOrderLineRequestOptionalProperty[]
): ReadonlyArray<TransferOrderLineRequestOptionalProperty> {
    return properties;
}

export function instanceOfTransferOrderLineRequest(value: object): value is TransferOrderLineRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createTransferOrderLineRequestPropertyNames('requestedQty', 'sku', );
    const optionalStringProperties = createTransferOrderLineRequestOptionalProperties({ name: 'sku', nullable: false }, );
    const optionalNumberProperties = createTransferOrderLineRequestOptionalProperties({ name: 'requestedQty', nullable: false }, );
    const optionalBooleanProperties = createTransferOrderLineRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalTransferOrderLineRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalTransferOrderLineRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalTransferOrderLineRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

