/**
 * POS Human Resources Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkIngestResult } from './bulkIngestResult';


export interface BulkIngestResponse { 
    totalSubmitted?: number;
    successCount?: number;
    failureCount?: number;
    results?: Array<BulkIngestResult>;
}

