/**
 * POS Human Resources Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeContactInfoDto } from './employeeContactInfoDto';


export interface CreateEmployeeRequest { 
    legalName: string;
    preferredName?: string;
    employeeNumber: string;
    status: CreateEmployeeRequestStatusEnum;
    hireDate: string;
    terminationDate?: string;
    contactInfo?: EmployeeContactInfoDto;
    duplicatePolicy?: CreateEmployeeRequestDuplicatePolicyEnum;
}
export enum CreateEmployeeRequestStatusEnum {
    Active = 'ACTIVE',
    OnLeave = 'ON_LEAVE',
    Suspended = 'SUSPENDED',
    Terminated = 'TERMINATED',
    Disabled = 'DISABLED'
};
export enum CreateEmployeeRequestDuplicatePolicyEnum {
    Strict = 'STRICT',
    Balanced = 'BALANCED'
};



function isOptionalCreateEmployeeRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CreateEmployeeRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCreateEmployeeRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCreateEmployeeRequestOptionalProperties(
    ...properties: CreateEmployeeRequestOptionalProperty[]
): ReadonlyArray<CreateEmployeeRequestOptionalProperty> {
    return properties;
}

export function instanceOfCreateEmployeeRequest(value: object): value is CreateEmployeeRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCreateEmployeeRequestPropertyNames('legalName', 'employeeNumber', 'status', 'hireDate', );
    const optionalStringProperties = createCreateEmployeeRequestOptionalProperties({ name: 'legalName', nullable: false }, { name: 'preferredName', nullable: false }, { name: 'employeeNumber', nullable: false }, { name: 'status', nullable: false }, { name: 'duplicatePolicy', nullable: false }, );
    const optionalNumberProperties = createCreateEmployeeRequestOptionalProperties();
    const optionalBooleanProperties = createCreateEmployeeRequestOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCreateEmployeeRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCreateEmployeeRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCreateEmployeeRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

