/**
 * POS Human Resources Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmployeeContactInfoDto } from './employeeContactInfoDto';


export interface EmployeeProfileDto { 
    id?: string;
    legalName?: string;
    preferredName?: string;
    employeeNumber?: string;
    status?: EmployeeProfileDtoStatusEnum;
    hireDate?: string;
    terminationDate?: string;
    contactInfo?: EmployeeContactInfoDto;
    statusEffectiveAt?: string;
    warnings?: Array<string>;
}
export enum EmployeeProfileDtoStatusEnum {
    Active = 'ACTIVE',
    OnLeave = 'ON_LEAVE',
    Suspended = 'SUSPENDED',
    Terminated = 'TERMINATED',
    Disabled = 'DISABLED'
};



