/**
 * POS Security Service API
 * API documentation for POS Security Service
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditLogEventDto { 
    eventId?: string;
    timestamp?: string;
    eventType?: string;
    actorId?: string;
    entityId?: string;
    entityType?: string;
    oldValue?: string;
    newValue?: string;
    context?: string;
}

