/**
 * POS Security Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPersonLinkBulkIngestRecord } from './userPersonLinkBulkIngestRecord';


/**
 * Generic bulk ingest request: a batch of records for a job scoped to a location
 */
export interface BulkIngestRequestUserPersonLinkBulkIngestRecord {
    /**
     * Identifier of the bulk ingest job
     */
    jobId: string;
    /**
     * Location the records are ingested for
     */
    locationId: string;
    /**
     * Identifier of the operator submitting the batch
     */
    operatorId?: string;
    /**
     * The records to ingest (at least one); shape depends on the target domain
     */
    records: Array<UserPersonLinkBulkIngestRecord>;
}

function isOptionalBulkIngestRequestUserPersonLinkBulkIngestRecordPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type BulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createBulkIngestRequestUserPersonLinkBulkIngestRecordPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createBulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperties(
    ...properties: BulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperty[]
): ReadonlyArray<BulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperty> {
    return properties;
}

export function instanceOfBulkIngestRequestUserPersonLinkBulkIngestRecord(value: object): value is BulkIngestRequestUserPersonLinkBulkIngestRecord {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createBulkIngestRequestUserPersonLinkBulkIngestRecordPropertyNames('jobId', 'locationId', 'records', );
    const optionalStringProperties = createBulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperties({ name: 'jobId', nullable: false }, { name: 'locationId', nullable: false }, { name: 'operatorId', nullable: false }, );
    const optionalNumberProperties = createBulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperties();
    const optionalBooleanProperties = createBulkIngestRequestUserPersonLinkBulkIngestRecordOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalBulkIngestRequestUserPersonLinkBulkIngestRecordPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalBulkIngestRequestUserPersonLinkBulkIngestRecordPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalBulkIngestRequestUserPersonLinkBulkIngestRecordPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

