/**
 * POS Security Service API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response containing both access and refresh JWT tokens
 */
export interface TokenPairResponse { 
    /**
     * Short-lived JWT access token (1 hour expiration)
     */
    accessToken?: string;
    /**
     * Long-lived JWT refresh token (7 days expiration)
     */
    refreshToken?: string;
}

export function instanceOfTokenPairResponse(value: object): value is TokenPairResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;
    const _v = value as Record<string, unknown>;
    if ('accessToken' in _v && typeof _v['accessToken'] !== 'string') return false;
    if ('refreshToken' in _v && typeof _v['refreshToken'] !== 'string') return false;
    return true;
}

