/**
 * Positivity Price API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request payload to create a product sale-restriction rule
 */
export interface CreateRestrictionRuleRequest { 
    /**
     * Product the restriction rule applies to
     */
    productId: string;
    /**
     * Location scope tag for the restriction
     */
    locationTag: CreateRestrictionRuleRequestLocationTagEnum;
    /**
     * Service channel scope tag for the restriction
     */
    serviceTag: CreateRestrictionRuleRequestServiceTagEnum;
    /**
     * Date the restriction rule becomes effective
     */
    effectiveFrom: string;
    /**
     * Optional date the restriction rule stops being effective
     */
    effectiveTo?: string;
    /**
     * Optional pricing policy version associated with the rule
     */
    policyVersion?: number;
    /**
     * Whether the restriction can be overridden with authorization
     */
    overrideable: boolean;
}
export enum CreateRestrictionRuleRequestLocationTagEnum {
    AllLocations = 'ALL_LOCATIONS',
    RetailStore = 'RETAIL_STORE',
    Warehouse = 'WAREHOUSE',
    MobileService = 'MOBILE_SERVICE',
    Franchise = 'FRANCHISE',
    TestLocation = 'TEST_LOCATION'
};
export enum CreateRestrictionRuleRequestServiceTagEnum {
    PosSale = 'POS_SALE',
    Workorder = 'WORKORDER',
    Estimate = 'ESTIMATE',
    Invoice = 'INVOICE',
    Delivery = 'DELIVERY'
};



function isOptionalCreateRestrictionRuleRequestPropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type CreateRestrictionRuleRequestOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createCreateRestrictionRuleRequestPropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createCreateRestrictionRuleRequestOptionalProperties(
    ...properties: CreateRestrictionRuleRequestOptionalProperty[]
): ReadonlyArray<CreateRestrictionRuleRequestOptionalProperty> {
    return properties;
}

export function instanceOfCreateRestrictionRuleRequest(value: object): value is CreateRestrictionRuleRequest {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createCreateRestrictionRuleRequestPropertyNames('productId', 'locationTag', 'serviceTag', 'effectiveFrom', 'overrideable', );
    const optionalStringProperties = createCreateRestrictionRuleRequestOptionalProperties({ name: 'productId', nullable: false }, { name: 'locationTag', nullable: false }, { name: 'serviceTag', nullable: false }, );
    const optionalNumberProperties = createCreateRestrictionRuleRequestOptionalProperties({ name: 'policyVersion', nullable: false }, );
    const optionalBooleanProperties = createCreateRestrictionRuleRequestOptionalProperties({ name: 'overrideable', nullable: false }, );

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalCreateRestrictionRuleRequestPropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalCreateRestrictionRuleRequestPropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalCreateRestrictionRuleRequestPropertyOfType(_v, property.name, 'boolean', property.nullable));
}

