/**
 * Positivity Price API
 * Price service for managing product pricing and discounts
 *
 * The version of the OpenAPI document: v1
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Optional account/vehicle context used to evaluate promotion eligibility
 */
export interface EligibilityContext { 
    /**
     * Customer account identifier
     */
    accountId?: string | null;
    /**
     * Vehicle identifier used for vehicle-based eligibility rules
     */
    vehicleId?: string | null;
}

