/**
 * Positivity Price API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoneyAmount } from './moneyAmount';
import { PricingBreakdownEntry } from './pricingBreakdownEntry';


/**
 * Calculated contextual price quote response
 */
export interface PriceQuoteResponse { 
    /**
     * Product identifier
     */
    productId?: string;
    /**
     * Quoted quantity
     */
    quantity?: number;
    /**
     * Manufacturer suggested retail price
     */
    msrp?: MoneyAmount;
    /**
     * Final unit price after applying applicable rules
     */
    unitPrice?: MoneyAmount;
    /**
     * Extended price (unit price multiplied by quantity)
     */
    extendedPrice?: MoneyAmount;
    /**
     * Source from which the final price was resolved
     */
    priceSource?: string;
    /**
     * Per-rule pricing breakdown entries
     */
    pricingBreakdown?: Array<PricingBreakdownEntry>;
    /**
     * Non-fatal warnings generated during quote calculation
     */
    warnings?: Array<string>;
}

function isOptionalPriceQuoteResponsePropertyOfType(
    value: Record<string, unknown>,
    propertyName: string,
    propertyType: 'string' | 'number' | 'boolean',
    isNullable = false
): boolean {
    if (!(propertyName in value)) {
        return true;
    }

    const propertyValue = value[propertyName];
    if (isNullable && propertyValue === null) {
        return true;
    }

    return typeof propertyValue === propertyType;
}

type PriceQuoteResponseOptionalProperty = Readonly<{
    name: string;
    nullable: boolean;
}>;

function createPriceQuoteResponsePropertyNames(...propertyNames: string[]): ReadonlyArray<string> {
    return propertyNames;
}

function createPriceQuoteResponseOptionalProperties(
    ...properties: PriceQuoteResponseOptionalProperty[]
): ReadonlyArray<PriceQuoteResponseOptionalProperty> {
    return properties;
}

export function instanceOfPriceQuoteResponse(value: object): value is PriceQuoteResponse {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return false;

    const _v = value as Record<string, unknown>;

    const requiredProperties = createPriceQuoteResponsePropertyNames();
    const optionalStringProperties = createPriceQuoteResponseOptionalProperties({ name: 'productId', nullable: false }, { name: 'priceSource', nullable: false }, );
    const optionalNumberProperties = createPriceQuoteResponseOptionalProperties({ name: 'quantity', nullable: false }, );
    const optionalBooleanProperties = createPriceQuoteResponseOptionalProperties();

    return requiredProperties.every((propertyName) => propertyName in _v && _v[propertyName] !== undefined)
        && optionalStringProperties.every((property) => isOptionalPriceQuoteResponsePropertyOfType(_v, property.name, 'string', property.nullable))
        && optionalNumberProperties.every((property) => isOptionalPriceQuoteResponsePropertyOfType(_v, property.name, 'number', property.nullable))
        && optionalBooleanProperties.every((property) => isOptionalPriceQuoteResponsePropertyOfType(_v, property.name, 'boolean', property.nullable));
}

