/**
 * Positivity Price API
 *
 * Contact: louis.burroughs@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestrictionEvaluationItem { 
    productId: string;
    locationTag: RestrictionEvaluationItemLocationTagEnum;
    serviceTag: RestrictionEvaluationItemServiceTagEnum;
    context: RestrictionEvaluationItemContextEnum;
}
export enum RestrictionEvaluationItemLocationTagEnum {
    AllLocations = 'ALL_LOCATIONS',
    RetailStore = 'RETAIL_STORE',
    Warehouse = 'WAREHOUSE',
    MobileService = 'MOBILE_SERVICE',
    Franchise = 'FRANCHISE',
    TestLocation = 'TEST_LOCATION'
};
export enum RestrictionEvaluationItemServiceTagEnum {
    PosSale = 'POS_SALE',
    Workorder = 'WORKORDER',
    Estimate = 'ESTIMATE',
    Invoice = 'INVOICE',
    Delivery = 'DELIVERY'
};
export enum RestrictionEvaluationItemContextEnum {
    Browse = 'BROWSE',
    Quote = 'QUOTE',
    Checkout = 'CHECKOUT',
    InvoiceFinalize = 'INVOICE_FINALIZE',
    CommitSale = 'COMMIT_SALE'
};



