export * from './appointmentsAPI.service';
import { AppointmentsAPIService } from './appointmentsAPI.service';
export * from './assignmentController.service';
import { AssignmentControllerService } from './assignmentController.service';
export * from './conflictOverrideAPI.service';
import { ConflictOverrideAPIService } from './conflictOverrideAPI.service';
export * from './scheduleAPI.service';
import { ScheduleAPIService } from './scheduleAPI.service';
export * from './shopAPI.service';
import { ShopAPIService } from './shopAPI.service';
export * from './shopAuditController.service';
import { ShopAuditControllerService } from './shopAuditController.service';
export * from './shopBayAPI.service';
import { ShopBayAPIService } from './shopBayAPI.service';
export * from './shopMobileUnitAPI.service';
import { ShopMobileUnitAPIService } from './shopMobileUnitAPI.service';
export * from './workorderOperationalContextAPI.service';
import { WorkorderOperationalContextAPIService } from './workorderOperationalContextAPI.service';
export const APIS = [AppointmentsAPIService, AssignmentControllerService, ConflictOverrideAPIService, ScheduleAPIService, ShopAPIService, ShopAuditControllerService, ShopBayAPIService, ShopMobileUnitAPIService, WorkorderOperationalContextAPIService];
