export * from './catalogAPI.service';
import { CatalogAPIService } from './catalogAPI.service';
export * from './catalogBulkIngestAPI.service';
import { CatalogBulkIngestAPIService } from './catalogBulkIngestAPI.service';
export * from './catalogItemsAPI.service';
import { CatalogItemsAPIService } from './catalogItemsAPI.service';
export * from './itemCostAPI.service';
import { ItemCostAPIService } from './itemCostAPI.service';
export * from './priceBookAPI.service';
import { PriceBookAPIService } from './priceBookAPI.service';
export * from './productMSRPAPI.service';
import { ProductMSRPAPIService } from './productMSRPAPI.service';
export * from './productsAPI.service';
import { ProductsAPIService } from './productsAPI.service';
export * from './supplierItemCostAPI.service';
import { SupplierItemCostAPIService } from './supplierItemCostAPI.service';
export * from './supplierItemCostListAPI.service';
import { SupplierItemCostListAPIService } from './supplierItemCostListAPI.service';
export * from './uOMConversionAPI.service';
import { UOMConversionAPIService } from './uOMConversionAPI.service';
export const APIS = [CatalogAPIService, CatalogBulkIngestAPIService, CatalogItemsAPIService, ItemCostAPIService, PriceBookAPIService, ProductMSRPAPIService, ProductsAPIService, SupplierItemCostAPIService, SupplierItemCostListAPIService, UOMConversionAPIService];
